export type Season = "春" | "夏" | "秋" | "冬";
export type WeatherStyle = "晴天" | "曇天" | "雨天";
export type Duration = 30 | 60 | 90;

export interface Course {
  id: number;
  name: string;
  duration: Duration;
  distance: number; // 距離（km）
  area: string;
  seasons: Season[];
  weatherStyles: WeatherStyle[];
  description: string;
  startPoint?: string; // スタート地点（住所または場所名）
  endPoint?: string;   // ゴール地点（住所または場所名）
}

// 距離をフォーマットする関数
export function formatDistance(distance: number): string {
  return `${distance.toFixed(1)}km`;
}

// Google Mapsの経路表示URLを生成
export function getGoogleMapsUrl(course: Course): string {
  // スタートとゴールが設定されている場合は経路表示
  if (course.startPoint && course.endPoint) {
    const origin = encodeURIComponent(course.startPoint);
    const destination = encodeURIComponent(course.endPoint);
    return `https://www.google.com/maps/dir/?api=1&origin=${origin}&destination=${destination}&travelmode=walking`;
  }

  // 設定されていない場合は検索表示
  const query = encodeURIComponent(`${course.name} ${course.area}`);
  return `https://www.google.com/maps/search/?api=1&query=${query}`;
}

// Google Maps埋め込みURLを生成
export function getGoogleMapsEmbedUrl(course: Course): string {
  const query = encodeURIComponent(`${course.name} ${course.area}`);
  return `https://www.google.com/maps/embed/v1/place?key=YOUR_API_KEY&q=${query}`;
}

export const courses: Course[] = [
  // 春のコース
  {
    id: 1,
    name: "目黒川の桜道",
    duration: 60,
    distance: 4.5,
    area: "中目黒",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "約800本の桜が川沿いに続く人気スポット。春の陽気な散歩に最適です。",
    startPoint: "中目黒駅",
    endPoint: "池尻大橋駅",
  },
  {
    id: 2,
    name: "上野公園の桜散策",
    duration: 90,
    distance: 6.8,
    area: "上野",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "広大な敷地に約1200本の桜。博物館や動物園も楽しめる充実コースです。",
    startPoint: "上野駅",
    endPoint: "鶯谷駅",
  },
  {
    id: 3,
    name: "千鳥ヶ淵の桜トンネル",
    duration: 30,
    distance: 2.3,
    area: "千代田区",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "皇居のお堀沿いに続く桜のトンネル。都心の静かな散歩道です。",
    startPoint: "九段下駅",
    endPoint: "半蔵門駅",
  },

  // 夏のコース
  {
    id: 4,
    name: "等々力渓谷の涼散歩",
    duration: 60,
    distance: 4.2,
    area: "等々力",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "東京23区唯一の渓谷。木陰と川のせせらぎで涼しく過ごせます。",
    startPoint: "等々力駅",
    endPoint: "等々力不動尊",
  },
  {
    id: 5,
    name: "昭和記念公園の緑道",
    duration: 90,
    distance: 7.0,
    area: "立川",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "広大な敷地の木陰道。噴水エリアで涼むこともできる夏の定番コースです。",
    startPoint: "立川駅",
    endPoint: "昭島駅",
  },
  {
    id: 6,
    name: "浜離宮恩賜庭園散策",
    duration: 30,
    distance: 2.0,
    area: "汐留",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "海風が心地よい潮入の池がある庭園。都会のオアシスです。",
    startPoint: "汐留駅",
    endPoint: "築地市場駅",
  },
  {
    id: 7,
    name: "お台場海浜公園の夕涼み",
    duration: 60,
    distance: 4.8,
    area: "お台場",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "レインボーブリッジを眺めながら海沿いを散歩。夕方からがおすすめです。",
    startPoint: "お台場海浜公園駅",
    endPoint: "台場駅",
  },

  // 秋のコース
  {
    id: 8,
    name: "明治神宮外苑のイチョウ並木",
    duration: 30,
    distance: 2.2,
    area: "青山",
    seasons: ["秋"],
    weatherStyles: ["晴天", "曇天"],
    description: "146本のイチョウが作る黄金のトンネル。秋の東京を代表する景色です。",
    startPoint: "青山一丁目駅",
    endPoint: "外苑前駅",
  },
  {
    id: 9,
    name: "六義園の紅葉散策",
    duration: 60,
    distance: 4.5,
    area: "駒込",
    seasons: ["秋"],
    weatherStyles: ["晴天", "曇天"],
    description: "美しい日本庭園で紅葉を楽しむ。ライトアップ時期もおすすめです。",
    startPoint: "駒込駅",
    endPoint: "巣鴨駅",
  },
  {
    id: 10,
    name: "代々木公園の紅葉道",
    duration: 90,
    distance: 6.5,
    area: "代々木",
    seasons: ["秋"],
    weatherStyles: ["晴天", "曇天"],
    description: "広い芝生と色づく木々。ゆったりと秋を感じられる都会のオアシスです。",
    startPoint: "原宿駅",
    endPoint: "代々木公園駅",
  },
  {
    id: 11,
    name: "国営昭和記念公園の銀杏並木",
    duration: 90,
    distance: 7.2,
    area: "立川",
    seasons: ["秋"],
    weatherStyles: ["晴天", "曇天"],
    description: "200mに渡る黄金のイチョウ並木。広大な敷地でゆったり散策できます。",
    startPoint: "西立川駅",
    endPoint: "立川駅",
  },

  // 冬のコース
  {
    id: 12,
    name: "皇居東御苑の静寂散歩",
    duration: 60,
    distance: 4.3,
    area: "大手町",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "冬の凛とした空気の中、江戸城跡を巡る歴史散歩が楽しめます。",
    startPoint: "大手町駅",
    endPoint: "竹橋駅",
  },
  {
    id: 13,
    name: "築地場外市場の食べ歩き散歩",
    duration: 30,
    distance: 2.1,
    area: "築地",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "温かい食べ物を楽しみながら散策。冬の寒さも忘れる美味しい散歩です。",
    startPoint: "築地市場駅",
    endPoint: "築地駅",
  },
  {
    id: 14,
    name: "丸の内イルミネーション散策",
    duration: 60,
    distance: 4.0,
    area: "丸の内",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "美しいイルミネーションが街を彩る冬の夜の散歩コース。",
    startPoint: "東京駅",
    endPoint: "有楽町駅",
  },

  // オールシーズン（晴天）
  {
    id: 15,
    name: "浅草寺と仲見世通り散策",
    duration: 60,
    distance: 4.5,
    area: "浅草",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "東京を代表する観光スポット。下町情緒あふれる散歩が楽しめます。",
    startPoint: "浅草駅",
    endPoint: "東京スカイツリー",
  },
  {
    id: 16,
    name: "谷中銀座の下町散歩",
    duration: 30,
    distance: 2.3,
    area: "谷中",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "昭和レトロな商店街と猫がいる街。ゆったりとした時間が流れます。",
    startPoint: "日暮里駅",
    endPoint: "根津駅",
  },
  {
    id: 17,
    name: "表参道・原宿ストリート散歩",
    duration: 90,
    distance: 6.8,
    area: "表参道",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "最新トレンドとおしゃれなカフェが並ぶ街を散策。",
    startPoint: "原宿駅",
    endPoint: "表参道駅",
  },

  // 雨天対応コース
  {
    id: 18,
    name: "東京駅地下街探検",
    duration: 30,
    distance: 2.0,
    area: "東京駅",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["雨天", "曇天"],
    description: "広大な地下街を探検。雨を気にせず、グルメやショッピングを楽しめます。",
    startPoint: "東京駅八重洲口",
    endPoint: "東京駅丸の内口",
  },
  {
    id: 19,
    name: "新宿地下街散策",
    duration: 60,
    distance: 4.0,
    area: "新宿",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["雨天", "曇天"],
    description: "迷宮のような地下街を散策。雨の日でも快適に歩き回れます。",
    startPoint: "新宿駅西口",
    endPoint: "新宿三丁目駅",
  },
  {
    id: 20,
    name: "渋谷スクランブルスクエア周辺",
    duration: 30,
    distance: 2.2,
    area: "渋谷",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["雨天", "曇天"],
    description: "屋内施設が充実。展望台や商業施設を巡る都市型散歩。",
    startPoint: "渋谷駅",
    endPoint: "渋谷ヒカリエ",
  },
  {
    id: 21,
    name: "六本木ヒルズ・ミッドタウン散策",
    duration: 60,
    distance: 4.3,
    area: "六本木",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["雨天", "曇天"],
    description: "アートと商業施設を楽しむ雨天対応コース。屋内移動が中心です。",
    startPoint: "六本木駅",
    endPoint: "乃木坂駅",
  },
  {
    id: 22,
    name: "アメ横商店街散策",
    duration: 30,
    distance: 2.1,
    area: "上野",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["雨天", "曇天"],
    description: "屋根のあるアーケード街。雨でも活気ある下町の雰囲気を楽しめます。",
    startPoint: "上野駅",
    endPoint: "御徒町駅",
  },

  // 追加の季節限定コース
  {
    id: 23,
    name: "井の頭公園の新緑散歩",
    duration: 60,
    distance: 4.6,
    area: "吉祥寺",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "池の周りを新緑が彩る季節。ボートに乗るのもおすすめです。",
    startPoint: "吉祥寺駅",
    endPoint: "井の頭公園駅",
  },
  {
    id: 24,
    name: "隅田川テラスの夏夕涼み",
    duration: 90,
    distance: 7.5,
    area: "浅草・スカイツリー",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "川沿いを歩きながらスカイツリーを眺める。夕方からがベストです。",
    startPoint: "浅草駅",
    endPoint: "とうきょうスカイツリー駅",
  },
  {
    id: 25,
    name: "新宿御苑の紅葉巡り",
    duration: 90,
    distance: 6.7,
    area: "新宿",
    seasons: ["秋"],
    weatherStyles: ["晴天", "曇天"],
    description: "広大な庭園で多様な紅葉を楽しむ。都会とは思えない静けさです。",
    startPoint: "新宿御苑前駅",
    endPoint: "新宿三丁目駅",
  },
  {
    id: 26,
    name: "深大寺の初詣散歩",
    duration: 60,
    distance: 4.4,
    area: "調布",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "厳かな雰囲気の古刹と蕎麦屋巡り。冬の澄んだ空気が心地よいコースです。",
    startPoint: "調布駅",
    endPoint: "深大寺",
  },

  // 追加コース（春）
  {
    id: 27,
    name: "小石川後楽園の桜と庭園",
    duration: 60,
    distance: 4.1,
    area: "後楽園",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "江戸時代の大名庭園で桜と新緑を楽しむ。水戸黄門ゆかりの地です。",
    startPoint: "後楽園駅",
    endPoint: "飯田橋駅",
  },
  {
    id: 28,
    name: "神楽坂の石畳散歩",
    duration: 30,
    distance: 2.4,
    area: "神楽坂",
    seasons: ["春", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "情緒ある石畳の坂道と路地裏を散策。隠れ家的なカフェやレストランが魅力です。",
    startPoint: "飯田橋駅",
    endPoint: "神楽坂駅",
  },

  // 追加コース（夏）
  {
    id: 29,
    name: "清澄庭園の涼散歩",
    duration: 60,
    distance: 4.3,
    area: "清澄白河",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "池と石が美しい回遊式庭園。木陰で涼みながらゆったり散策できます。",
    startPoint: "清澄白河駅",
    endPoint: "門前仲町駅",
  },
  {
    id: 30,
    name: "二子玉川河川敷散歩",
    duration: 90,
    distance: 6.9,
    area: "二子玉川",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "多摩川沿いの広々とした河川敷。川風が心地よい夏の散歩コースです。",
    startPoint: "二子玉川駅",
    endPoint: "二子新地駅",
  },

  // 追加コース（秋）
  {
    id: 31,
    name: "小金井公園の紅葉散策",
    duration: 90,
    distance: 7.3,
    area: "小金井",
    seasons: ["秋"],
    weatherStyles: ["晴天", "曇天"],
    description: "都内屈指の広さを誇る公園。紅葉の木々が美しく、ゆったり散策できます。",
    startPoint: "武蔵小金井駅",
    endPoint: "花小金井駅",
  },
  {
    id: 32,
    name: "自由が丘の街歩き",
    duration: 60,
    distance: 4.4,
    area: "自由が丘",
    seasons: ["春", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "おしゃれなショップやカフェが並ぶ街。落ち着いた雰囲気の散歩が楽しめます。",
    startPoint: "自由が丘駅",
    endPoint: "奥沢駅",
  },

  // 追加コース（冬）
  {
    id: 33,
    name: "恵比寿ガーデンプレイス散策",
    duration: 30,
    distance: 2.5,
    area: "恵比寿",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "冬のイルミネーションが美しい複合施設。おしゃれなレストランも充実です。",
    startPoint: "恵比寿駅",
    endPoint: "代官山駅",
  },
  {
    id: 34,
    name: "品川シーサイド散歩",
    duration: 60,
    distance: 4.7,
    area: "品川",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "運河沿いの遊歩道を散策。近代的なビル群と水辺の景色が楽しめます。",
    startPoint: "品川駅",
    endPoint: "天王洲アイル駅",
  },

  // オールシーズン追加
  {
    id: 35,
    name: "下北沢の古着屋巡り",
    duration: 60,
    distance: 4.2,
    area: "下北沢",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "個性的なショップやライブハウスが並ぶサブカルチャーの街。散策が楽しい街です。",
    startPoint: "下北沢駅",
    endPoint: "世田谷代田駅",
  },
  {
    id: 36,
    name: "吉祥寺サンロード商店街",
    duration: 30,
    distance: 2.2,
    area: "吉祥寺",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["雨天", "曇天"],
    description: "アーケード商店街で雨の日でも快適。グルメやショッピングが楽しめます。",
    startPoint: "吉祥寺駅",
    endPoint: "吉祥寺駅北口",
  },

  // 夜景コース（20個）
  {
    id: 37,
    name: "レインボーブリッジ遊歩道",
    duration: 60,
    distance: 4.5,
    area: "お台場",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "東京湾の夜景を一望できる橋上の遊歩道。夕暮れから夜にかけてが絶景です。",
    startPoint: "芝浦ふ頭駅",
    endPoint: "お台場海浜公園駅",
  },
  {
    id: 38,
    name: "東京タワー周辺夜景散歩",
    duration: 60,
    distance: 4.3,
    area: "芝公園",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "ライトアップされた東京タワーを様々な角度から楽しむ夜景コース。",
    startPoint: "赤羽橋駅",
    endPoint: "神谷町駅",
  },
  {
    id: 39,
    name: "スカイツリー夜景散歩",
    duration: 90,
    distance: 6.5,
    area: "押上",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "ライトアップされたスカイツリーを眺めながら隅田川沿いを散策。",
    startPoint: "押上駅",
    endPoint: "浅草駅",
  },
  {
    id: 40,
    name: "汐留シオサイト夜景",
    duration: 30,
    distance: 2.3,
    area: "汐留",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "高層ビル群の夜景と電通本社ビルのイルミネーションが美しいエリア。",
    startPoint: "汐留駅",
    endPoint: "新橋駅",
  },
  {
    id: 41,
    name: "豊洲ぐるり公園夜景",
    duration: 60,
    distance: 4.8,
    area: "豊洲",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "運河沿いの遊歩道から見る東京湾の夜景。レインボーブリッジも望めます。",
    startPoint: "豊洲駅",
    endPoint: "市場前駅",
  },
  {
    id: 42,
    name: "晴海運河夜景散歩",
    duration: 90,
    distance: 7.0,
    area: "晴海",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "運河沿いの遊歩道から眺める都心の夜景。静かで落ち着いた雰囲気です。",
    startPoint: "勝どき駅",
    endPoint: "晴海トリトン",
  },
  {
    id: 43,
    name: "新宿副都心夜景",
    duration: 60,
    distance: 4.2,
    area: "新宿",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "高層ビル群が作り出す都会的な夜景を楽しむ散歩コース。",
    startPoint: "新宿駅西口",
    endPoint: "都庁前駅",
  },
  {
    id: 44,
    name: "品川インターシティ夜景",
    duration: 30,
    distance: 2.4,
    area: "品川",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "品川のオフィス街の夜景とイルミネーションを楽しむ都市型散歩。",
    startPoint: "品川駅",
    endPoint: "北品川駅",
  },
  {
    id: 45,
    name: "有明ガーデン夜景",
    duration: 30,
    distance: 2.1,
    area: "有明",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "商業施設のイルミネーションと東京湾の夜景を楽しめるスポット。",
    startPoint: "有明駅",
    endPoint: "有明テニスの森駅",
  },
  {
    id: 46,
    name: "月島もんじゃ夜散歩",
    duration: 60,
    distance: 4.0,
    area: "月島",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "下町の夜の雰囲気ともんじゃ焼きの灯りが温かい散歩道。",
    startPoint: "月島駅",
    endPoint: "勝どき駅",
  },
  {
    id: 47,
    name: "天王洲アイル夜景",
    duration: 60,
    distance: 4.6,
    area: "天王洲",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "運河沿いのボードウォークから見る水辺の夜景が美しいエリア。",
    startPoint: "天王洲アイル駅",
    endPoint: "品川シーサイド駅",
  },
  {
    id: 48,
    name: "隅田川テラス夜景",
    duration: 90,
    distance: 7.2,
    area: "墨田区",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "隅田川沿いの遊歩道からスカイツリーと橋のライトアップを楽しむ。",
    startPoint: "浅草駅",
    endPoint: "両国駅",
  },
  {
    id: 49,
    name: "銀座夜景ストリート",
    duration: 60,
    distance: 4.4,
    area: "銀座",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "高級ブランド店のウィンドウと街灯が作る洗練された夜の銀座を散策。",
    startPoint: "銀座駅",
    endPoint: "有楽町駅",
  },
  {
    id: 50,
    name: "目黒川イルミネーション",
    duration: 60,
    distance: 4.3,
    area: "中目黒",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "冬季限定のイルミネーションが川面に映る幻想的な夜景スポット。",
    startPoint: "中目黒駅",
    endPoint: "池尻大橋駅",
  },
  {
    id: 51,
    name: "ゲートブリッジ夜景",
    duration: 90,
    distance: 6.8,
    area: "若洲",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "恐竜のような形のゲートブリッジを歩いて渡る。東京湾の夜景が壮大です。",
    startPoint: "新木場駅",
    endPoint: "若洲海浜公園",
  },
  {
    id: 52,
    name: "竹芝桟橋夜景",
    duration: 30,
    distance: 2.2,
    area: "竹芝",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "東京湾に浮かぶ船と対岸の夜景を楽しめる静かなスポット。",
    startPoint: "竹芝駅",
    endPoint: "浜松町駅",
  },
  {
    id: 53,
    name: "アークヒルズ夜景",
    duration: 30,
    distance: 2.0,
    area: "六本木",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "都心の高層ビル群の夜景とアートを楽しむ洗練された散歩道。",
    startPoint: "六本木一丁目駅",
    endPoint: "溜池山王駅",
  },
  {
    id: 54,
    name: "豊洲市場周辺夜景",
    duration: 60,
    distance: 4.1,
    area: "豊洲",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "市場の活気と東京湾の夜景を同時に楽しめるユニークなコース。",
    startPoint: "市場前駅",
    endPoint: "豊洲駅",
  },
  {
    id: 55,
    name: "秋葉原電気街夜景",
    duration: 60,
    distance: 4.0,
    area: "秋葉原",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "ネオンとLEDが輝く電気街の独特な夜景を楽しむサブカル散歩。",
    startPoint: "秋葉原駅",
    endPoint: "末広町駅",
  },
  {
    id: 56,
    name: "表参道イルミネーション",
    duration: 60,
    distance: 4.5,
    area: "表参道",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "ケヤキ並木のイルミネーションが美しい冬の定番夜景スポット。",
    startPoint: "表参道駅",
    endPoint: "原宿駅",
  },

  // 春の季節限定コース（6個）
  {
    id: 57,
    name: "飛鳥山公園の桜",
    duration: 60,
    distance: 4.2,
    area: "王子",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "江戸時代から続く桜の名所。約650本の桜が咲き誇ります。",
    startPoint: "王子駅",
    endPoint: "西ヶ原駅",
  },
  {
    id: 58,
    name: "石神井公園の桜と新緑",
    duration: 90,
    distance: 6.9,
    area: "石神井",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "池の周りを彩る桜と新緑。ボートからの眺めも楽しめます。",
    startPoint: "石神井公園駅",
    endPoint: "大泉学園駅",
  },
  {
    id: 59,
    name: "隅田公園桜まつり",
    duration: 60,
    distance: 4.6,
    area: "浅草",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "隅田川沿いに約1,000本の桜。スカイツリーと桜のコラボレーション。",
    startPoint: "浅草駅",
    endPoint: "押上駅",
  },
  {
    id: 60,
    name: "砧公園ファミリー桜散歩",
    duration: 90,
    distance: 7.1,
    area: "用賀",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "広大な芝生と約840本の桜。ピクニックにも最適な公園です。",
    startPoint: "用賀駅",
    endPoint: "千歳船橋駅",
  },
  {
    id: 61,
    name: "播磨坂さくら並木",
    duration: 30,
    distance: 2.3,
    area: "文京区",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "約150本の桜のトンネル。地元で愛される隠れた名所です。",
    startPoint: "茗荷谷駅",
    endPoint: "江戸川橋駅",
  },
  {
    id: 62,
    name: "光が丘公園の桜",
    duration: 60,
    distance: 4.8,
    area: "光が丘",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "広大な芝生広場と桜並木。ゆったりとした春の散歩が楽しめます。",
    startPoint: "光が丘駅",
    endPoint: "練馬春日町駅",
  },

  // 夏の季節限定コース（8個）
  {
    id: 63,
    name: "葛西臨海公園海風散歩",
    duration: 90,
    distance: 7.3,
    area: "葛西",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "海沿いの公園で潮風を感じながら散策。観覧車からの眺めも楽しめます。",
    startPoint: "葛西臨海公園駅",
    endPoint: "葛西駅",
  },
  {
    id: 64,
    name: "砧公園の木陰散歩",
    duration: 60,
    distance: 4.5,
    area: "用賀",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "木陰が多く夏でも涼しい公園。広い芝生でリフレッシュできます。",
    startPoint: "用賀駅",
    endPoint: "祖師ヶ谷大蔵駅",
  },
  {
    id: 65,
    name: "水元公園の涼散歩",
    duration: 90,
    distance: 6.7,
    area: "金町",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "都内最大級の水郷公園。水辺の涼しさと豊かな自然を楽しめます。",
    startPoint: "金町駅",
    endPoint: "亀有駅",
  },
  {
    id: 66,
    name: "駒沢オリンピック公園",
    duration: 60,
    distance: 4.3,
    area: "駒沢",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "木陰が豊富なジョギングコース。スポーツ施設も充実しています。",
    startPoint: "駒沢大学駅",
    endPoint: "桜新町駅",
  },
  {
    id: 67,
    name: "野川公園の自然散策",
    duration: 90,
    distance: 7.0,
    area: "調布",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "野川沿いの自然豊かな公園。川のせせらぎが涼しげです。",
    startPoint: "西武多摩川駅",
    endPoint: "武蔵境駅",
  },
  {
    id: 68,
    name: "芝公園の緑陰散歩",
    duration: 30,
    distance: 2.4,
    area: "芝公園",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "東京タワーを眺めながら木陰で涼む都心のオアシス。",
    startPoint: "芝公園駅",
    endPoint: "御成門駅",
  },
  {
    id: 69,
    name: "舎人公園の夏散歩",
    duration: 60,
    distance: 4.7,
    area: "舎人",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "広大な芝生と大池。日暮里・舎人ライナーでアクセス便利です。",
    startPoint: "舎人公園駅",
    endPoint: "見沼代親水公園駅",
  },
  {
    id: 70,
    name: "多摩川河川敷サイクリングロード",
    duration: 90,
    distance: 7.5,
    area: "多摩川",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "多摩川沿いの広々とした遊歩道。川風が心地よい夏の定番コース。",
    startPoint: "二子玉川駅",
    endPoint: "登戸駅",
  },

  // 秋の季節限定コース（6個）
  {
    id: 71,
    name: "高尾山紅葉ハイキング",
    duration: 90,
    distance: 6.5,
    area: "高尾",
    seasons: ["秋"],
    weatherStyles: ["晴天", "曇天"],
    description: "都心から1時間の紅葉の名所。ケーブルカーで気軽にアクセスできます。",
    startPoint: "高尾山口駅",
    endPoint: "高尾山頂",
  },
  {
    id: 72,
    name: "殿ヶ谷戸庭園の紅葉",
    duration: 30,
    distance: 2.1,
    area: "国分寺",
    seasons: ["秋"],
    weatherStyles: ["晴天", "曇天"],
    description: "崖線の地形を活かした庭園。紅葉の美しさは都内屈指です。",
    startPoint: "国分寺駅",
    endPoint: "西国分寺駅",
  },
  {
    id: 73,
    name: "井の頭公園紅葉散策",
    duration: 60,
    distance: 4.4,
    area: "吉祥寺",
    seasons: ["秋"],
    weatherStyles: ["晴天", "曇天"],
    description: "池の周りを彩る紅葉。ボートから眺める紅葉も格別です。",
    startPoint: "吉祥寺駅",
    endPoint: "井の頭公園駅",
  },
  {
    id: 74,
    name: "旧古河庭園の秋バラと紅葉",
    duration: 60,
    distance: 4.0,
    area: "西ヶ原",
    seasons: ["秋"],
    weatherStyles: ["晴天", "曇天"],
    description: "洋館と日本庭園が融合。秋バラと紅葉の共演が見事です。",
    startPoint: "上中里駅",
    endPoint: "駒込駅",
  },
  {
    id: 75,
    name: "浜離宮恩賜庭園秋景色",
    duration: 60,
    distance: 4.1,
    area: "汐留",
    seasons: ["秋"],
    weatherStyles: ["晴天", "曇天"],
    description: "潮入の池と紅葉のコントラスト。都心のビル群を背景にした紅葉が美しい。",
    startPoint: "汐留駅",
    endPoint: "新橋駅",
  },
  {
    id: 76,
    name: "石神井公園紅葉巡り",
    duration: 90,
    distance: 6.8,
    area: "石神井",
    seasons: ["秋"],
    weatherStyles: ["晴天", "曇天"],
    description: "三宝寺池と石神井池の周りを彩る紅葉。静かな秋の散策が楽しめます。",
    startPoint: "石神井公園駅",
    endPoint: "大泉学園駅",
  },

  // 冬の季節限定コース（6個）
  {
    id: 77,
    name: "大手町イルミネーション",
    duration: 30,
    distance: 2.2,
    area: "大手町",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "オフィス街のイルミネーションが幻想的。仕事帰りに立ち寄れます。",
    startPoint: "大手町駅",
    endPoint: "東京駅",
  },
  {
    id: 78,
    name: "よみうりランド ジュエルミネーション",
    duration: 90,
    distance: 6.2,
    area: "稲城",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "関東最大級のイルミネーション。550万球の光の世界です。",
    startPoint: "京王よみうりランド駅",
    endPoint: "よみうりランド",
  },
  {
    id: 79,
    name: "カレッタ汐留イルミネーション",
    duration: 30,
    distance: 2.0,
    area: "汐留",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天", "雨天"],
    description: "屋内でも楽しめるイルミネーション。音楽とのコラボレーションが見事です。",
    startPoint: "汐留駅",
    endPoint: "新橋駅",
  },
  {
    id: 80,
    name: "代々木公園冬景色",
    duration: 60,
    distance: 4.3,
    area: "原宿",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "冬の澄んだ空気の中、静かな公園を散策。都会の喧騒を忘れられます。",
    startPoint: "原宿駅",
    endPoint: "代々木公園駅",
  },
  {
    id: 81,
    name: "日比谷公園冬散歩",
    duration: 30,
    distance: 2.3,
    area: "日比谷",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "都心の憩いの場。冬の凛とした空気が心地よい散歩道です。",
    startPoint: "日比谷駅",
    endPoint: "有楽町駅",
  },
  {
    id: 82,
    name: "東京ミッドタウン冬の庭",
    duration: 60,
    distance: 4.0,
    area: "六本木",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "洗練されたイルミネーションと冬の庭園。大人の冬散歩に最適です。",
    startPoint: "六本木駅",
    endPoint: "乃木坂駅",
  },

  // グルメ散歩コース（8個）
  {
    id: 83,
    name: "戸越銀座商店街グルメ巡り",
    duration: 60,
    distance: 4.2,
    area: "戸越銀座",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "都内最長の商店街で食べ歩き。コロッケや和菓子が人気です。",
    startPoint: "戸越銀座駅",
    endPoint: "戸越公園駅",
  },
  {
    id: 84,
    name: "佃・月島もんじゃストリート",
    duration: 60,
    distance: 4.5,
    area: "月島",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "もんじゃ焼きの聖地。70店以上のもんじゃ屋が軒を連ねます。",
    startPoint: "月島駅",
    endPoint: "勝どき駅",
  },
  {
    id: 85,
    name: "巣鴨地蔵通り商店街",
    duration: 30,
    distance: 2.4,
    area: "巣鴨",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "おばあちゃんの原宿。塩大福や赤パンツが名物の下町商店街です。",
    startPoint: "巣鴨駅",
    endPoint: "庚申塚駅",
  },
  {
    id: 86,
    name: "両国ちゃんこ鍋巡り",
    duration: 60,
    distance: 4.0,
    area: "両国",
    seasons: ["秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "相撲の街で本格ちゃんこ鍋。江戸東京博物館も楽しめます。",
    startPoint: "両国駅",
    endPoint: "森下駅",
  },
  {
    id: 87,
    name: "門前仲町深川めし散歩",
    duration: 60,
    distance: 4.3,
    area: "門前仲町",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "深川めしと下町グルメ。富岡八幡宮の参拝も楽しめます。",
    startPoint: "門前仲町駅",
    endPoint: "清澄白河駅",
  },
  {
    id: 88,
    name: "人形町甘酒横丁",
    duration: 30,
    distance: 2.2,
    area: "人形町",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "老舗の和菓子店やせんべい屋が並ぶ情緒ある通り。",
    startPoint: "人形町駅",
    endPoint: "水天宮前駅",
  },
  {
    id: 89,
    name: "高円寺阿波おどり通り",
    duration: 60,
    distance: 4.1,
    area: "高円寺",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "個性的な飲食店が集まるサブカルの街。古着屋巡りも楽しめます。",
    startPoint: "高円寺駅",
    endPoint: "新高円寺駅",
  },
  {
    id: 90,
    name: "中野ブロードウェイ探検",
    duration: 60,
    distance: 4.0,
    area: "中野",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天", "雨天"],
    description: "サブカルチャーの聖地。マニアックなショップとグルメが楽しめます。",
    startPoint: "中野駅",
    endPoint: "新中野駅",
  },

  // 歴史・文化コース（6個）
  {
    id: 91,
    name: "柴又帝釈天参道",
    duration: 60,
    distance: 4.4,
    area: "柴又",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "寅さんの街。江戸情緒あふれる参道と帝釈天を巡ります。",
    startPoint: "柴又駅",
    endPoint: "京成金町駅",
  },
  {
    id: 92,
    name: "根津神社つつじ散歩",
    duration: 30,
    distance: 2.3,
    area: "根津",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "約3,000株のつつじが咲く歴史ある神社。文京区の隠れた名所です。",
    startPoint: "根津駅",
    endPoint: "千駄木駅",
  },
  {
    id: 93,
    name: "増上寺と東京タワー",
    duration: 60,
    distance: 4.2,
    area: "芝公園",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "徳川家の菩提寺と東京タワーのコントラスト。歴史と現代が交差します。",
    startPoint: "芝公園駅",
    endPoint: "大門駅",
  },
  {
    id: 94,
    name: "護国寺と音羽の杜",
    duration: 30,
    distance: 2.4,
    area: "護国寺",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "徳川綱吉ゆかりの寺院。静かな境内で心が落ち着きます。",
    startPoint: "護国寺駅",
    endPoint: "江戸川橋駅",
  },
  {
    id: 95,
    name: "寛永寺と上野の杜",
    duration: 90,
    distance: 6.6,
    area: "上野",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "徳川家ゆかりの寺院群。上野公園の歴史散策が楽しめます。",
    startPoint: "上野駅",
    endPoint: "日暮里駅",
  },
  {
    id: 96,
    name: "亀戸天神と藤の花",
    duration: 60,
    distance: 4.3,
    area: "亀戸",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "学問の神様と美しい藤の花。スカイツリーを背景にした境内が絶景です。",
    startPoint: "亀戸駅",
    endPoint: "錦糸町駅",
  },

  // 雨天対応コース（4個）
  {
    id: 97,
    name: "池袋サンシャインシティ",
    duration: 60,
    distance: 4.0,
    area: "池袋",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["雨天", "曇天"],
    description: "水族館、展望台、ショッピングが楽しめる複合施設。雨でも一日遊べます。",
    startPoint: "池袋駅",
    endPoint: "東池袋駅",
  },
  {
    id: 98,
    name: "お台場ヴィーナスフォート",
    duration: 90,
    distance: 6.5,
    area: "お台場",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["雨天", "曇天"],
    description: "屋内型テーマパーク。中世ヨーロッパの街並みを再現した商業施設です。",
    startPoint: "青海駅",
    endPoint: "お台場海浜公園駅",
  },
  {
    id: 99,
    name: "二子玉川ライズ",
    duration: 60,
    distance: 4.2,
    area: "二子玉川",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["雨天", "曇天"],
    description: "ショッピングとグルメが充実。雨の日でも快適に過ごせる商業施設です。",
    startPoint: "二子玉川駅",
    endPoint: "二子新地駅",
  },
  {
    id: 100,
    name: "立川ルミネ・伊勢丹",
    duration: 30,
    distance: 2.1,
    area: "立川",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["雨天", "曇天"],
    description: "立川駅直結の商業施設。雨を気にせずショッピングが楽しめます。",
    startPoint: "立川駅",
    endPoint: "立川北駅",
  },
];
