export type Season = "春" | "夏" | "秋" | "冬";
export type WeatherStyle = "晴天" | "曇天" | "雨天";
export type Duration = 30 | 60 | 90;

export interface Course {
  id: number;
  name: string;
  duration: Duration;
  distance: number; // 距離（km）
  area: string;
  seasons: Season[];
  weatherStyles: WeatherStyle[];
  description: string;
  startPoint?: string; // スタート地点（住所または場所名）
  endPoint?: string;   // ゴール地点（住所または場所名）
  waypoints?: string[]; // 経由地点（観光スポットなど）
  durationNote?: string; // 所要時間に関する注釈
  highlights?: string[]; // 見どころポイント
  recommendedTimes?: string[]; // おすすめの時間帯（朝・昼・夕方・夜）
  difficulty?: "初心者向け" | "中級者向け" | "上級者向け"; // 難易度
  accessInfo?: string; // アクセス情報（最寄り駅からの所要時間など）
}

// 距離をフォーマットする関数
export function formatDistance(distance: number): string {
  return `${distance.toFixed(1)}km`;
}

// Google Mapsの経路表示URLを生成
export function getGoogleMapsUrl(course: Course): string {
  // スタートとゴールが設定されている場合は経路表示
  if (course.startPoint && course.endPoint) {
    const origin = encodeURIComponent(course.startPoint);
    const destination = encodeURIComponent(course.endPoint);

    // 経由地点がある場合は追加
    let url = `https://www.google.com/maps/dir/?api=1&origin=${origin}&destination=${destination}`;

    if (course.waypoints && course.waypoints.length > 0) {
      const waypoints = course.waypoints.map(wp => encodeURIComponent(wp)).join('|');
      url += `&waypoints=${waypoints}`;
    }

    url += '&travelmode=walking';
    return url;
  }

  // 設定されていない場合は検索表示
  const query = encodeURIComponent(`${course.name} ${course.area}`);
  return `https://www.google.com/maps/search/?api=1&query=${query}`;
}

// Google Maps埋め込みURLを生成
export function getGoogleMapsEmbedUrl(course: Course): string {
  const query = encodeURIComponent(`${course.name} ${course.area}`);
  return `https://www.google.com/maps/embed/v1/place?key=YOUR_API_KEY&q=${query}`;
}

export const courses: Course[] = [
  // 春のコース
  {
    id: 1,
    name: "目黒川の桜道",
    duration: 60,
    distance: 4.5,
    area: "中目黒",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "約800本の桜が川沿いに続く人気スポット。春の陽気な散歩に最適です。",
    startPoint: "中目黒駅",
    endPoint: "池尻大橋駅",
    waypoints: ["目黒川沿い", "中目黒公園"],
    durationNote: "桜の鑑賞や写真撮影の時間を含む目安時間です",
    highlights: ["川沿いに続く約800本の桜並木", "おしゃれなカフェやレストランが充実", "ライトアップされた夜桜も楽しめる", "中目黒公園で休憩可能"],
    recommendedTimes: ["昼", "夕方", "夜"],
    difficulty: "初心者向け",
    accessInfo: "中目黒駅から徒歩1分、平坦な川沿いの道",
  },
  {
    id: 2,
    name: "上野公園の桜散策",
    duration: 90,
    distance: 6.8,
    area: "上野",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "広大な敷地に約1200本の桜。博物館や動物園も楽しめる充実コースです。",
    startPoint: "上野駅",
    endPoint: "鶯谷駅",
    waypoints: ["上野恩賜公園", "不忍池", "上野東照宮"],
    durationNote: "公園内の散策・観光・休憩時間を含みます",
    highlights: ["約1200本の桜並木", "不忍池の水上桜", "上野東照宮の歴史建築", "博物館・動物園も隣接"],
    recommendedTimes: ["朝", "昼"],
    difficulty: "初心者向け",
    accessInfo: "上野駅から徒歩2分、広大な公園内を巡る",
  },
  {
    id: 3,
    name: "千鳥ヶ淵の桜トンネル",
    duration: 30,
    distance: 2.3,
    area: "千代田区",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "皇居のお堀沿いに続く桜のトンネル。都心の静かな散歩道です。",
    startPoint: "九段下駅",
    endPoint: "半蔵門駅",
    waypoints: ["千鳥ヶ淵緑道"],
    durationNote: "桜を眺めながらゆっくり歩く時間です",
    highlights: ["皇居のお堀と桜のコントラスト", "ボート乗り場から見る水上の桜", "ライトアップされた幻想的な夜桜"],
    recommendedTimes: ["昼", "夕方", "夜"],
    difficulty: "初心者向け",
    accessInfo: "九段下駅から徒歩5分、平坦な緑道",
  },

  // 夏のコース
  {
    id: 4,
    name: "等々力渓谷の涼散歩",
    duration: 60,
    distance: 4.2,
    area: "等々力",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "東京23区唯一の渓谷。木陰と川のせせらぎで涼しく過ごせます。",
    startPoint: "等々力駅",
    endPoint: "等々力不動尊",
    waypoints: ["等々力渓谷", "等々力渓谷横穴"],
    durationNote: "渓谷内をゆっくり散策する時間です",
    highlights: ["23区唯一の渓谷で自然を満喫", "川のせせらぎと木陰で涼しい", "古墳時代の横穴古墳を見学", "等々力不動尊で休憩"],
    recommendedTimes: ["朝", "昼"],
    difficulty: "初心者向け",
    accessInfo: "等々力駅から徒歩3分、階段あり・渓谷内は涼しい",
  },
  {
    id: 5,
    name: "昭和記念公園の緑道",
    duration: 90,
    distance: 7.0,
    area: "立川",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "広大な敷地の木陰道。噴水エリアで涼むこともできる夏の定番コースです。",
    startPoint: "立川駅",
    endPoint: "昭島駅",
    waypoints: ["昭和記念公園", "レインボープール", "水のカーテン"],
    durationNote: "公園内を散策し、休憩を楽しむ時間です",
    highlights: ["165ヘクタールの広大な国営公園", "水のカーテンや噴水で涼める", "四季折々の花々が楽しめる", "サイクリングコースも完備"],
    recommendedTimes: ["朝", "昼"],
    difficulty: "初心者向け",
    accessInfo: "立川駅から徒歩10分、広大な公園内（入園料450円）",
  },
  {
    id: 6,
    name: "浜離宮恩賜庭園散策",
    duration: 30,
    distance: 2.0,
    area: "汐留",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "海風が心地よい潮入の池がある庭園。都会のオアシスです。",
    startPoint: "汐留駅",
    endPoint: "築地市場駅",
    waypoints: ["浜離宮恩賜庭園"],
    durationNote: "庭園内をゆっくり鑑賞する時間です",
    highlights: ["江戸時代の大名庭園", "東京湾の海水を取り入れた潮入の池", "高層ビル群とのコントラスト", "お茶屋で抹茶を楽しめる"],
    recommendedTimes: ["朝", "昼", "夕方"],
    difficulty: "初心者向け",
    accessInfo: "汐留駅から徒歩7分、庭園内は平坦（入園料300円）",
  },
  {
    id: 7,
    name: "お台場海浜公園の夕涼み",
    duration: 60,
    distance: 4.8,
    area: "お台場",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "レインボーブリッジを眺めながら海沿いを散歩。夕方からがおすすめです。",
    startPoint: "お台場海浜公園駅",
    endPoint: "台場駅",
    waypoints: ["お台場海浜公園", "自由の女神像"],
    durationNote: "海辺をゆっくり散策し、夕景を楽しむ時間です",
    highlights: ["レインボーブリッジの絶景", "海風が心地よい砂浜", "自由の女神像とのフォトスポット", "夕陽と夜景の両方を楽しめる"],
    recommendedTimes: ["夕方", "夜"],
    difficulty: "初心者向け",
    accessInfo: "お台場海浜公園駅から徒歩3分、海沿いの平坦な遊歩道",
  },

  // 秋のコース
  {
    id: 8,
    name: "明治神宮外苑のイチョウ並木",
    duration: 30,
    distance: 2.2,
    area: "青山",
    seasons: ["秋"],
    weatherStyles: ["晴天", "曇天"],
    description: "146本のイチョウが作る黄金のトンネル。秋の東京を代表する景色です。",
    startPoint: "青山一丁目駅",
    endPoint: "外苑前駅",
    waypoints: ["明治神宮外苑イチョウ並木"],
    durationNote: "イチョウ並木をゆっくり歩き、写真撮影を楽しむ時間です",
    highlights: ["146本のイチョウが作る黄金のトンネル", "絵画館を背景にした絶景", "フォトスポットとして大人気", "周辺にカフェやレストラン充実"],
    recommendedTimes: ["昼", "夕方"],
    difficulty: "初心者向け",
    accessInfo: "青山一丁目駅から徒歩5分、平坦な並木道",
  },
  {
    id: 9,
    name: "六義園の紅葉散策",
    duration: 60,
    distance: 4.5,
    area: "駒込",
    seasons: ["秋"],
    weatherStyles: ["晴天", "曇天"],
    description: "美しい日本庭園で紅葉を楽しむ。ライトアップ時期もおすすめです。",
    startPoint: "駒込駅",
    endPoint: "巣鴨駅",
    waypoints: ["六義園"],
    durationNote: "庭園内を散策し、紅葉を鑑賞する時間です",
    highlights: ["江戸時代の回遊式庭園", "約450本のイロハモミジ", "夜間ライトアップ期間あり", "お茶屋で抹茶を楽しめる"],
    recommendedTimes: ["昼", "夕方", "夜"],
    difficulty: "初心者向け",
    accessInfo: "駒込駅から徒歩7分、起伏のある庭園（入園料300円）",
  },
  {
    id: 10,
    name: "代々木公園の紅葉道",
    duration: 90,
    distance: 6.5,
    area: "代々木",
    seasons: ["秋"],
    weatherStyles: ["晴天", "曇天"],
    description: "広い芝生と色づく木々。ゆったりと秋を感じられる都会のオアシスです。",
    startPoint: "原宿駅",
    endPoint: "代々木公園駅",
    waypoints: ["代々木公園", "明治神宮"],
    highlights: ["54ヘクタールの広大な都市公園", "ケヤキやイチョウの紅葉", "明治神宮の森も散策可能", "週末はイベントやフリマも開催"],
    recommendedTimes: ["朝", "昼"],
    difficulty: "初心者向け",
    accessInfo: "原宿駅から徒歩3分、広い公園内を巡る",
    durationNote: "公園内を散策し、休憩を含む時間です",
  },
  {
    id: 11,
    name: "国営昭和記念公園の銀杏並木",
    duration: 90,
    distance: 7.2,
    area: "立川",
    seasons: ["秋"],
    weatherStyles: ["晴天", "曇天"],
    description: "200mに渡る黄金のイチョウ並木。広大な敷地でゆったり散策できます。",
    startPoint: "西立川駅",
    endPoint: "立川駅",
    waypoints: ["昭和記念公園", "かたらいのイチョウ並木", "日本庭園"],
    durationNote: "広大な公園内を散策し、休憩する時間です",
    highlights: ["200m続く圧巻のイチョウ並木", "日本庭園で紅葉も楽しめる", "165ヘクタールの広大な敷地", "サイクリングも可能"],
    recommendedTimes: ["昼", "夕方"],
    difficulty: "初心者向け",
    accessInfo: "西立川駅から徒歩2分、入園料450円",
  },

  // 冬のコース
  {
    id: 12,
    name: "皇居東御苑の静寂散歩",
    duration: 60,
    distance: 4.3,
    area: "大手町",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "冬の凛とした空気の中、江戸城跡を巡る歴史散歩が楽しめます。",
    startPoint: "大手町駅",
    endPoint: "竹橋駅",
    waypoints: ["皇居東御苑", "天守台跡"],
    durationNote: "庭園と史跡をゆっくり見学する時間です",
    highlights: ["江戸城天守台跡の歴史を感じる", "美しい日本庭園（二の丸庭園）", "無料で入場できる皇居の一部", "冬の澄んだ空気で散策快適"],
    recommendedTimes: ["朝", "昼"],
    difficulty: "初心者向け",
    accessInfo: "大手町駅から徒歩5分、無料入場・月金休園",
  },
  {
    id: 13,
    name: "築地場外市場の食べ歩き散歩",
    duration: 30,
    distance: 2.1,
    area: "築地",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "温かい食べ物を楽しみながら散策。冬の寒さも忘れる美味しい散歩です。",
    startPoint: "築地市場駅",
    endPoint: "築地駅",
    waypoints: ["築地場外市場"],
    durationNote: "食べ歩きとショッピングを楽しむ時間です",
    highlights: ["新鮮な海鮮丼や寿司が食べられる", "玉子焼きの名店が多数", "400以上の店舗が軒を連ねる", "プロも通う食材の宝庫"],
    recommendedTimes: ["朝", "昼"],
    difficulty: "初心者向け",
    accessInfo: "築地市場駅から徒歩1分、早朝から営業",
  },
  {
    id: 14,
    name: "丸の内イルミネーション散策",
    duration: 60,
    distance: 4.0,
    area: "丸の内",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "美しいイルミネーションが街を彩る冬の夜の散歩コース。",
    startPoint: "東京駅",
    endPoint: "有楽町駅",
    waypoints: ["丸の内仲通り", "東京国際フォーラム"],
    durationNote: "イルミネーションを眺めながらゆっくり歩く時間です",
    highlights: ["約120本の街路樹が輝くイルミネーション", "東京駅の赤レンガ駅舎のライトアップ", "高級ブランド店が並ぶおしゃれな街並み", "温かいカフェで休憩可能"],
    recommendedTimes: ["夜"],
    difficulty: "初心者向け",
    accessInfo: "東京駅から徒歩すぐ、平坦な舗装路",
  },

  // オールシーズン（晴天）
  {
    id: 15,
    name: "浅草寺と仲見世通り散策",
    duration: 60,
    distance: 4.5,
    area: "浅草",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "東京を代表する観光スポット。下町情緒あふれる散歩が楽しめます。",
    startPoint: "浅草駅",
    endPoint: "東京スカイツリー",
    waypoints: ["浅草寺", "仲見世通り", "雷門"],
    durationNote: "観光・参拝・ショッピングの時間を含みます",
    highlights: ["雷門と大提灯は必見のフォトスポット", "約250mの仲見世通りで食べ歩き", "浅草寺本堂で参拝", "スカイツリーを遠望できる"],
    recommendedTimes: ["朝", "昼", "夕方"],
    difficulty: "初心者向け",
    accessInfo: "浅草駅から徒歩1分、観光客で賑わう平坦な道",
  },
  {
    id: 16,
    name: "谷中銀座の下町散歩",
    duration: 30,
    distance: 2.3,
    area: "谷中",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "昭和レトロな商店街と猫がいる街。ゆったりとした時間が流れます。",
    startPoint: "日暮里駅",
    endPoint: "根津駅",
    waypoints: ["谷中銀座商店街", "夕やけだんだん"],
    durationNote: "商店街を散策し、食べ歩きを楽しむ時間です",
    highlights: ["夕やけだんだんから見る夕景が絶景", "猫に出会える下町風情", "メンチカツや焼きせんべいが人気", "昭和レトロな雰囲気を満喫"],
    recommendedTimes: ["昼", "夕方"],
    difficulty: "初心者向け",
    accessInfo: "日暮里駅から徒歩5分、平坦な商店街",
  },
  {
    id: 17,
    name: "表参道・原宿ストリート散歩",
    duration: 90,
    distance: 6.8,
    area: "表参道",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "最新トレンドとおしゃれなカフェが並ぶ街を散策。",
    startPoint: "原宿駅",
    endPoint: "表参道駅",
    waypoints: ["竹下通り", "明治神宮", "表参道ヒルズ"],
    durationNote: "ショッピングや休憩を楽しみながらの散策時間です",
    highlights: ["竹下通りの最新トレンド","明治神宮の緑豊かな参道","表参道ヒルズの洗練された空間","おしゃれなカフェやショップが充実"],
    recommendedTimes: ["昼","夕方"],
    difficulty: "初心者向け",
    accessInfo: "原宿駅から徒歩1分、にぎやかな通り",
  },

  // 雨天対応コース
  {
    id: 18,
    name: "東京駅地下街探検",
    duration: 30,
    distance: 2.0,
    area: "東京駅",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["雨天", "曇天"],
    description: "広大な地下街を探検。雨を気にせず、グルメやショッピングを楽しめます。",
    startPoint: "東京駅八重洲口",
    endPoint: "東京駅丸の内口",
    waypoints: ["八重洲地下街"],
    durationNote: "地下街を探検し、ショッピングを楽しむ時間です",
    highlights: ["八重洲地下街の約180店舗", "東京駅一番街のキャラクターストリート", "雨に濡れずに移動できる", "人気の駅弁や土産も充実"],
    recommendedTimes: ["朝", "昼", "夕方", "夜"],
    difficulty: "初心者向け",
    accessInfo: "東京駅構内、完全屋内で雨の日最適",
  },
  {
    id: 19,
    name: "新宿地下街散策",
    duration: 60,
    distance: 4.0,
    area: "新宿",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["雨天", "曇天"],
    description: "迷宮のような地下街を散策。雨の日でも快適に歩き回れます。",
    startPoint: "新宿駅西口",
    endPoint: "新宿三丁目駅",
    waypoints: ["新宿サブナード", "メトロプロムナード"],
    durationNote: "地下街を探索し、グルメやショッピングを楽しむ時間です",
    highlights: ["迷宮のような地下空間を探検","数百の飲食店やショップが集結","雨の日でも快適に散策","新宿駅からすべて直結"],
    recommendedTimes: ["昼","夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "新宿駅西口直結、完全屋内",
  },
  {
    id: 20,
    name: "渋谷スクランブルスクエア周辺",
    duration: 30,
    distance: 2.2,
    area: "渋谷",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["雨天", "曇天"],
    description: "屋内施設が充実。展望台や商業施設を巡る都市型散歩。",
    startPoint: "渋谷駅",
    endPoint: "渋谷ヒカリエ",
    waypoints: ["渋谷スクランブルスクエア"],
    durationNote: "商業施設をゆっくり見て回る時間です",
    highlights: ["SHIBUYA SKYの360度パノラマ展望","渋谷の最新スポットを巡る","屋内施設で快適に散策","フォトジェニックなスポット多数"],
    recommendedTimes: ["昼","夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "渋谷駅直結、展望台は入場料別途",
  },
  {
    id: 21,
    name: "六本木ヒルズ・ミッドタウン散策",
    duration: 60,
    distance: 4.3,
    area: "六本木",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["雨天", "曇天"],
    description: "アートと商業施設を楽しむ雨天対応コース。屋内移動が中心です。",
    startPoint: "六本木駅",
    endPoint: "乃木坂駅",
    waypoints: ["六本木ヒルズ", "東京ミッドタウン"],
    durationNote: "アート鑑賞とショッピングを楽しむ時間です",
    highlights: ["森美術館で現代アート鑑賞","東京シティビューの絶景","ミッドタウンの庭園が美しい","グルメやショッピングも充実"],
    recommendedTimes: ["昼","夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "六本木駅直結、美術館は入館料別途",
  },
  {
    id: 22,
    name: "アメ横商店街散策",
    duration: 30,
    distance: 2.1,
    area: "上野",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["雨天", "曇天"],
    description: "屋根のあるアーケード街。雨でも活気ある下町の雰囲気を楽しめます。",
    startPoint: "上野駅",
    endPoint: "御徒町駅",
    waypoints: ["アメヤ横丁"],
    durationNote: "商店街で食べ歩きやショッピングを楽しむ時間です",
    highlights: ["活気あふれる下町商店街","鮮魚や乾物の専門店が多数","お菓子や雑貨のお土産探し","アーケードで雨でも安心"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "上野駅から徒歩1分、アーケード商店街",
  },

  // 追加の季節限定コース
  {
    id: 23,
    name: "井の頭公園の新緑散歩",
    duration: 60,
    distance: 4.6,
    area: "吉祥寺",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "池の周りを新緑が彩る季節。ボートに乗るのもおすすめです。",
    startPoint: "吉祥寺駅",
    endPoint: "井の頭公園駅",
    waypoints: ["井の頭恩賜公園", "井の頭池"],
    durationNote: "公園内を散策し、ボート遊びなども楽しむ時間です",
    highlights: ["ボートから眺める池の景色","新緑に囲まれた憩いの場","井の頭自然文化園も隣接","カフェやレストランが充実"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "吉祥寺駅から徒歩5分、平坦な公園",
  },
  {
    id: 24,
    name: "隅田川テラスの夏夕涼み",
    duration: 90,
    distance: 7.5,
    area: "浅草・スカイツリー",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "川沿いを歩きながらスカイツリーを眺める。夕方からがベストです。",
    startPoint: "浅草駅",
    endPoint: "とうきょうスカイツリー駅",
    waypoints: ["吾妻橋", "隅田川テラス", "桜橋"],
    durationNote: "川沿いをゆっくり散策し、夕涼みを楽しむ時間です",
    highlights: ["スカイツリーを正面に眺める絶景","川沿いの遊歩道で夕涼み","隅田川に映る夕日が美しい","浅草の観光と組み合わせ可能"],
    recommendedTimes: ["夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "浅草駅から徒歩3分、平坦な遊歩道",
  },
  {
    id: 25,
    name: "新宿御苑の紅葉巡り",
    duration: 90,
    distance: 6.7,
    area: "新宿",
    seasons: ["秋"],
    weatherStyles: ["晴天", "曇天"],
    description: "広大な庭園で多様な紅葉を楽しむ。都会とは思えない静けさです。",
    startPoint: "新宿御苑前駅",
    endPoint: "新宿三丁目駅",
    waypoints: ["新宿御苑", "日本庭園", "フランス式整形庭園"],
    durationNote: "広大な庭園内を散策し、休憩を含む時間です",
    highlights: ["約1万本の木々が紅葉する","3つの庭園スタイルを楽しめる","都心とは思えない静寂","広々とした芝生でピクニック可"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "新宿御苑前駅から徒歩5分、入園料500円",
  },
  {
    id: 26,
    name: "深大寺の初詣散歩",
    duration: 60,
    distance: 4.4,
    area: "調布",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "厳かな雰囲気の古刹と蕎麦屋巡り。冬の澄んだ空気が心地よいコースです。",
    startPoint: "調布駅",
    endPoint: "深大寺",
    waypoints: ["深大寺", "深大寺そば通り"],
    durationNote: "参拝と蕎麦屋巡りを楽しむ時間です",
    highlights: ["厳かな古刹で心静かに参拝","名物の深大寺そばを堪能","神代植物公園も隣接","静かな森林浴が楽しめる"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "調布駅からバス15分、坂道あり",
  },

  // 追加コース（春）
  {
    id: 27,
    name: "小石川後楽園の桜と庭園",
    duration: 60,
    distance: 4.1,
    area: "後楽園",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "江戸時代の大名庭園で桜と新緑を楽しむ。水戸黄門ゆかりの地です。",
    startPoint: "後楽園駅",
    endPoint: "飯田橋駅",
    waypoints: ["小石川後楽園"],
    durationNote: "庭園内を散策し、桜と歴史を楽しむ時間です",
    highlights: ["江戸時代の大名庭園を堪能","水戸光圀ゆかりの歴史","四季折々の花々が咲く","東京ドームも近く観光に便利"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "後楽園駅から徒歩3分、入園料300円",
  },
  {
    id: 28,
    name: "神楽坂の石畳散歩",
    duration: 30,
    distance: 2.4,
    area: "神楽坂",
    seasons: ["春", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "情緒ある石畳の坂道と路地裏を散策。隠れ家的なカフェやレストランが魅力です。",
    startPoint: "飯田橋駅",
    endPoint: "神楽坂駅",
    waypoints: ["神楽坂通り", "兵庫横丁"],
    durationNote: "坂道や路地裏を散策し、カフェ休憩を楽しむ時間です",
    highlights: ["情緒ある石畳の坂道","隠れ家カフェやレストランが充実","路地裏散策が楽しい","フランス風の街並みも魅力"],
    recommendedTimes: ["昼","夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "飯田橋駅から徒歩3分、坂道あり",
  },

  // 追加コース（夏）
  {
    id: 29,
    name: "清澄庭園の涼散歩",
    duration: 60,
    distance: 4.3,
    area: "清澄白河",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "池と石が美しい回遊式庭園。木陰で涼みながらゆったり散策できます。",
    startPoint: "清澄白河駅",
    endPoint: "門前仲町駅",
    waypoints: ["清澄庭園", "深川図書館"],
    durationNote: "庭園内を散策し、カフェ休憩を楽しむ時間です",
    highlights: ["全国から集めた名石が美しい","池を巡る回遊式庭園","カフェの街・清澄白河も楽しめる","静かで落ち着いた雰囲気"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "清澄白河駅から徒歩3分、入園料150円",
  },
  {
    id: 30,
    name: "二子玉川河川敷散歩",
    duration: 90,
    distance: 6.9,
    area: "二子玉川",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "多摩川沿いの広々とした河川敷。川風が心地よい夏の散歩コースです。",
    startPoint: "二子玉川駅",
    endPoint: "二子新地駅",
    waypoints: ["多摩川河川敷", "兵庫島公園"],
    durationNote: "河川敷をゆっくり歩き、休憩する時間です",
    highlights: ["多摩川の開放的な景色","河川敷でBBQも可能","自然を感じながらリフレッシュ","二子玉川ライズでショッピングも"],
    recommendedTimes: ["朝","昼","夕方"],
    difficulty: "初心者向け",
    accessInfo: "二子玉川駅から徒歩5分、平坦な河川敷",
  },

  // 追加コース（秋）
  {
    id: 31,
    name: "小金井公園の紅葉散策",
    duration: 90,
    distance: 7.3,
    area: "小金井",
    seasons: ["秋"],
    weatherStyles: ["晴天", "曇天"],
    description: "都内屈指の広さを誇る公園。紅葉の木々が美しく、ゆったり散策できます。",
    startPoint: "武蔵小金井駅",
    endPoint: "花小金井駅",
    waypoints: ["小金井公園", "江戸東京たてもの園"],
    durationNote: "広大な公園内を散策し、歴史建築も楽しむ時間です",
    highlights: ["80ヘクタールの広大な公園","江戸東京たてもの園で歴史体験","紅葉の名所として有名","サイクリングも楽しめる"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "武蔵小金井駅からバス5分、入園無料",
  },
  {
    id: 32,
    name: "自由が丘の街歩き",
    duration: 60,
    distance: 4.4,
    area: "自由が丘",
    seasons: ["春", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "おしゃれなショップやカフェが並ぶ街。落ち着いた雰囲気の散歩が楽しめます。",
    startPoint: "自由が丘駅",
    endPoint: "奥沢駅",
    waypoints: ["ラ・ヴィータ", "自由が丘デパート"],
    durationNote: "ショッピングやカフェ休憩を楽しむ時間です",
    highlights: ["おしゃれなカフェが多数","ラ・ヴィータのヴェネツィア風街並み","スイーツの名店巡り","落ち着いた住宅街の雰囲気"],
    recommendedTimes: ["昼","夕方"],
    difficulty: "初心者向け",
    accessInfo: "自由が丘駅から徒歩1分、平坦な道",
  },

  // 追加コース（冬）
  {
    id: 33,
    name: "恵比寿ガーデンプレイス散策",
    duration: 30,
    distance: 2.5,
    area: "恵比寿",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "冬のイルミネーションが美しい複合施設。おしゃれなレストランも充実です。",
    startPoint: "恵比寿駅",
    endPoint: "代官山駅",
    waypoints: ["恵比寿ガーデンプレイス"],
    durationNote: "イルミネーション鑑賞とカフェ休憩を楽しむ時間です",
    highlights: ["バカラのシャンデリアが輝く","冬季イルミネーションが美しい","高級レストランでディナー","代官山へも徒歩圏内"],
    recommendedTimes: ["夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "恵比寿駅から動く歩道で5分",
  },
  {
    id: 34,
    name: "品川シーサイド散歩",
    duration: 60,
    distance: 4.7,
    area: "品川",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "運河沿いの遊歩道を散策。近代的なビル群と水辺の景色が楽しめます。",
    startPoint: "品川駅",
    endPoint: "天王洲アイル駅",
    waypoints: ["品川シーサイド", "天王洲ふれあい橋"],
    durationNote: "運河沿いをゆっくり歩く時間です",
    highlights: ["運河沿いの近代的な景観","天王洲アイルへ続く遊歩道","水辺のカフェで休憩","オフィス街と水辺のコントラスト"],
    recommendedTimes: ["昼","夕方"],
    difficulty: "初心者向け",
    accessInfo: "品川駅から徒歩10分、平坦な遊歩道",
  },

  // オールシーズン追加
  {
    id: 35,
    name: "下北沢の古着屋巡り",
    duration: 60,
    distance: 4.2,
    area: "下北沢",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "個性的なショップやライブハウスが並ぶサブカルチャーの街。散策が楽しい街です。",
    startPoint: "下北沢駅",
    endPoint: "世田谷代田駅",
    waypoints: ["下北沢一番街", "下北沢南口商店街"],
    durationNote: "古着屋やカフェ巡りを楽しむ時間です",
    highlights: ["個性的な古着屋が多数","ライブハウスやカフェ文化","サブカルチャーの発信地","路地裏散策が楽しい"],
    recommendedTimes: ["昼","夕方"],
    difficulty: "初心者向け",
    accessInfo: "下北沢駅から徒歩1分、坂道あり",
  },
  {
    id: 36,
    name: "吉祥寺サンロード商店街",
    duration: 30,
    distance: 2.2,
    area: "吉祥寺",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["雨天", "曇天"],
    description: "アーケード商店街で雨の日でも快適。グルメやショッピングが楽しめます。",
    startPoint: "吉祥寺駅",
    endPoint: "吉祥寺駅北口",
    waypoints: ["吉祥寺サンロード"],
    durationNote: "商店街でグルメやショッピングを楽しむ時間です",
    highlights: ["アーケードで雨でも安心","地元に愛される商店街","グルメやスイーツが充実","井の頭公園へのアクセス良好"],
    recommendedTimes: ["昼","夕方"],
    difficulty: "初心者向け",
    accessInfo: "吉祥寺駅から徒歩1分、アーケード商店街",
  },

  // 夜景コース（20個）
  {
    id: 37,
    name: "レインボーブリッジ遊歩道",
    duration: 60,
    distance: 4.5,
    area: "お台場",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "東京湾の夜景を一望できる橋上の遊歩道。夕暮れから夜にかけてが絶景です。",
    startPoint: "芝浦ふ頭駅",
    endPoint: "お台場海浜公園駅",
    waypoints: ["レインボーブリッジ遊歩道"],
    durationNote: "橋をゆっくり渡り、夜景を楽しむ時間です",
    highlights: ["東京湾を一望する1.7kmの遊歩道", "お台場と都心のビル群を両側から眺望", "海風が心地よい橋上散歩", "夕暮れから夜のライトアップまで楽しめる"],
    recommendedTimes: ["夕方", "夜"],
    difficulty: "中級者向け",
    accessInfo: "芝浦ふ頭駅から徒歩10分、長い橋を渡る・無料",
  },
  {
    id: 38,
    name: "東京タワー周辺夜景散歩",
    duration: 60,
    distance: 4.3,
    area: "芝公園",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "ライトアップされた東京タワーを様々な角度から楽しむ夜景コース。",
    startPoint: "赤羽橋駅",
    endPoint: "神谷町駅",
    waypoints: ["東京タワー", "芝公園"],
    durationNote: "タワー周辺を散策し、夜景撮影を楽しむ時間です",
    highlights: ["ライトアップされた333mの東京タワー", "様々な角度からタワーを撮影できる", "芝公園からの眺めが絶景", "展望台に上って都心の夜景も楽しめる"],
    recommendedTimes: ["夕方", "夜"],
    difficulty: "初心者向け",
    accessInfo: "赤羽橋駅から徒歩5分、タワー周辺を巡る",
  },
  {
    id: 39,
    name: "スカイツリー夜景散歩",
    duration: 90,
    distance: 6.5,
    area: "押上",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "ライトアップされたスカイツリーを眺めながら隅田川沿いを散策。",
    startPoint: "押上駅",
    endPoint: "浅草駅",
    waypoints: ["東京スカイツリー", "隅田川テラス", "吾妻橋"],
    durationNote: "夜景鑑賞やカフェ休憩を含む時間です",
    highlights: ["世界一高い634mのスカイツリーライトアップ", "隅田川に映るタワーの姿が幻想的", "川沿いの遊歩道から絶景を楽しめる", "ソラマチでショッピングやグルメも"],
    recommendedTimes: ["夕方", "夜"],
    difficulty: "初心者向け",
    accessInfo: "押上駅直結、川沿いの平坦な遊歩道",
  },
  {
    id: 40,
    name: "汐留シオサイト夜景",
    duration: 30,
    distance: 2.3,
    area: "汐留",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "高層ビル群の夜景と電通本社ビルのイルミネーションが美しいエリア。",
    startPoint: "汐留駅",
    endPoint: "新橋駅",
    waypoints: ["汐留シオサイト"],
    durationNote: "ビル群の夜景をゆっくり楽しむ時間です",
    highlights: ["高層ビル群の夜景","電通ビルのイルミネーション","浜離宮への通り道","日本テレビの大時計も見られる"],
    recommendedTimes: ["夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "汐留駅直結、平坦な歩行者デッキ",
  },
  {
    id: 41,
    name: "豊洲ぐるり公園夜景",
    duration: 60,
    distance: 4.8,
    area: "豊洲",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "運河沿いの遊歩道から見る東京湾の夜景。レインボーブリッジも望めます。",
    startPoint: "豊洲駅",
    endPoint: "市場前駅",
    waypoints: ["豊洲ぐるり公園", "ららぽーと豊洲"],
    durationNote: "運河沿いを散策し、夜景を楽しむ時間です",
    highlights: ["レインボーブリッジを一望","運河沿いの夜景が美しい","ららぽーと豊洲でショッピング","芝生広場でくつろげる"],
    recommendedTimes: ["夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "豊洲駅から徒歩5分、平坦な遊歩道",
  },
  {
    id: 42,
    name: "晴海運河夜景散歩",
    duration: 90,
    distance: 7.0,
    area: "晴海",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "運河沿いの遊歩道から眺める都心の夜景。静かで落ち着いた雰囲気です。",
    startPoint: "勝どき駅",
    endPoint: "晴海トリトン",
    waypoints: ["朝潮運河", "晴海ふ頭公園"],
    durationNote: "夜景を楽しみながらゆっくり歩く時間です",
    highlights: ["静かな運河沿いの遊歩道","選手村跡地のオリンピックレガシー","高層マンション群の夜景","穴場の夜景スポット"],
    recommendedTimes: ["夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "勝どき駅から徒歩5分、平坦な道",
  },
  {
    id: 43,
    name: "新宿副都心夜景",
    duration: 60,
    distance: 4.2,
    area: "新宿",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "高層ビル群が作り出す都会的な夜景を楽しむ散歩コース。",
    startPoint: "新宿駅西口",
    endPoint: "都庁前駅",
    waypoints: ["新宿住友ビル", "東京都庁"],
    durationNote: "高層ビル街をゆっくり歩き、夜景を楽しむ時間です",
    highlights: ["都庁展望室は無料で夜景鑑賞","超高層ビル群を見上げる","新宿の煌めく夜景","都庁展望室からの眺めは必見"],
    recommendedTimes: ["夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "新宿駅西口から徒歩10分、都庁展望室無料",
  },
  {
    id: 44,
    name: "品川インターシティ夜景",
    duration: 30,
    distance: 2.4,
    area: "品川",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "品川のオフィス街の夜景とイルミネーションを楽しむ都市型散歩。",
    startPoint: "品川駅",
    endPoint: "北品川駅",
    waypoints: ["品川インターシティ"],
    durationNote: "オフィス街の夜景を楽しむ時間です",
    highlights: ["品川駅直結で便利","運河沿いの夜景","ホテルやレストランが充実","オフィス街のライトアップ"],
    recommendedTimes: ["夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "品川駅直結、平坦な歩行者デッキ",
  },
  {
    id: 45,
    name: "有明ガーデン夜景",
    duration: 30,
    distance: 2.1,
    area: "有明",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "商業施設のイルミネーションと東京湾の夜景を楽しめるスポット。",
    startPoint: "有明駅",
    endPoint: "有明テニスの森駅",
    waypoints: ["有明ガーデン"],
    durationNote: "商業施設とウォーターフロントを楽しむ時間です",
    highlights: ["商業施設のイルミネーション","東京湾の夜景を一望","ショッピングと夜景を同時に","有明アリーナも近い"],
    recommendedTimes: ["夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "有明駅から徒歩3分",
  },
  {
    id: 46,
    name: "月島もんじゃ夜散歩",
    duration: 60,
    distance: 4.0,
    area: "月島",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "下町の夜の雰囲気ともんじゃ焼きの灯りが温かい散歩道。",
    startPoint: "月島駅",
    endPoint: "勝どき駅",
    waypoints: ["もんじゃストリート", "月島西仲通り商店街"],
    durationNote: "もんじゃ焼きを食べながら散策する時間です",
    highlights: ["70店以上のもんじゃ屋","下町の温かい雰囲気","食後の運河散策が気持ちいい","夜も賑わう商店街"],
    recommendedTimes: ["夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "月島駅から徒歩1分",
  },
  {
    id: 47,
    name: "天王洲アイル夜景",
    duration: 60,
    distance: 4.6,
    area: "天王洲",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "運河沿いのボードウォークから見る水辺の夜景が美しいエリア。",
    startPoint: "天王洲アイル駅",
    endPoint: "品川シーサイド駅",
    waypoints: ["天王洲ボードウォーク", "寺田倉庫"],
    durationNote: "運河沿いを散策し、アート作品も楽しむ時間です",
    highlights: ["水辺のボードウォーク","アート作品が点在","倉庫街のおしゃれな雰囲気","静かな運河の夜景"],
    recommendedTimes: ["夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "天王洲アイル駅から徒歩3分",
  },
  {
    id: 48,
    name: "隅田川テラス夜景",
    duration: 90,
    distance: 7.2,
    area: "墨田区",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "隅田川沿いの遊歩道からスカイツリーと橋のライトアップを楽しむ。",
    startPoint: "浅草駅",
    endPoint: "両国駅",
    waypoints: ["隅田川テラス", "吾妻橋", "駒形橋"],
    durationNote: "川沿いをゆっくり歩き、夜景を楽しむ時間です",
    highlights: ["スカイツリーのライトアップ","橋のイルミネーション","川面に映る光が幻想的","浅草からの続きにおすすめ"],
    recommendedTimes: ["夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "浅草駅から徒歩3分、川沿いの遊歩道",
  },
  {
    id: 49,
    name: "銀座夜景ストリート",
    duration: 60,
    distance: 4.4,
    area: "銀座",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "高級ブランド店のウィンドウと街灯が作る洗練された夜の銀座を散策。",
    startPoint: "銀座駅",
    endPoint: "有楽町駅",
    waypoints: ["銀座中央通り", "銀座和光"],
    durationNote: "ウィンドウショッピングを楽しみながら散策する時間です",
    highlights: ["高級ブランド店のウィンドウ","和光の時計塔が美しい","歩行者天国の週末がおすすめ","カフェやバーも充実"],
    recommendedTimes: ["夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "銀座駅から徒歩1分、平坦な通り",
  },
  {
    id: 50,
    name: "目黒川イルミネーション",
    duration: 60,
    distance: 4.3,
    area: "中目黒",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "冬季限定のイルミネーションが川面に映る幻想的な夜景スポット。",
    startPoint: "中目黒駅",
    endPoint: "池尻大橋駅",
    waypoints: ["目黒川沿い"],
    durationNote: "イルミネーションをゆっくり楽しむ時間です",
    highlights: ["川面に映るイルミネーション","冬季限定の幻想的な光景","デートスポットとして人気","周辺カフェで温まれる"],
    recommendedTimes: ["夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "中目黒駅から徒歩1分、冬季限定",
  },
  {
    id: 51,
    name: "ゲートブリッジ夜景",
    duration: 90,
    distance: 6.8,
    area: "若洲",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "恐竜のような形のゲートブリッジを歩いて渡る。東京湾の夜景が壮大です。",
    startPoint: "新木場駅",
    endPoint: "若洲海浜公園",
    waypoints: ["東京ゲートブリッジ"],
    durationNote: "橋を渡り、東京湾の夜景を楽しむ時間です",
    highlights: ["恐竜のような橋の形状","東京湾の大パノラマ","橋を歩いて渡れる貴重な体験","壮大な夜景を堪能"],
    recommendedTimes: ["夕方","夜"],
    difficulty: "中級者向け",
    accessInfo: "新木場駅からバス20分、橋上は風が強い",
  },
  {
    id: 52,
    name: "竹芝桟橋夜景",
    duration: 30,
    distance: 2.2,
    area: "竹芝",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "東京湾に浮かぶ船と対岸の夜景を楽しめる静かなスポット。",
    startPoint: "竹芝駅",
    endPoint: "浜松町駅",
    waypoints: ["竹芝桟橋"],
    durationNote: "海辺をゆっくり散策する時間です",
    highlights: ["東京湾の静かな夜景","離島行きフェリー乗り場","穴場のウォーターフロント","竹芝客船ターミナルの雰囲気"],
    recommendedTimes: ["夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "竹芝駅から徒歩3分",
  },
  {
    id: 53,
    name: "アークヒルズ夜景",
    duration: 30,
    distance: 2.0,
    area: "六本木",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "都心の高層ビル群の夜景とアートを楽しむ洗練された散歩道。",
    startPoint: "六本木一丁目駅",
    endPoint: "溜池山王駅",
    waypoints: ["アークヒルズ"],
    durationNote: "アートと夜景を楽しむ時間です",
    highlights: ["高層ビルに囲まれた庭園","アート作品が点在","六本木と赤坂の夜景","落ち着いた大人の雰囲気"],
    recommendedTimes: ["夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "六本木一丁目駅直結",
  },
  {
    id: 54,
    name: "豊洲市場周辺夜景",
    duration: 60,
    distance: 4.1,
    area: "豊洲",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "市場の活気と東京湾の夜景を同時に楽しめるユニークなコース。",
    startPoint: "市場前駅",
    endPoint: "豊洲駅",
    waypoints: ["豊洲市場", "豊洲公園"],
    durationNote: "市場周辺を散策し、夜景を楽しむ時間です",
    highlights: ["早朝の市場の活気（翌朝）","運河沿いの夜景","豊洲公園からの眺め","新しい東京の水辺エリア"],
    recommendedTimes: ["夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "市場前駅から徒歩1分",
  },
  {
    id: 55,
    name: "秋葉原電気街夜景",
    duration: 60,
    distance: 4.0,
    area: "秋葉原",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "ネオンとLEDが輝く電気街の独特な夜景を楽しむサブカル散歩。",
    startPoint: "秋葉原駅",
    endPoint: "末広町駅",
    waypoints: ["秋葉原電気街", "ラジオ会館"],
    durationNote: "電気街を散策し、サブカルチャーを楽しむ時間です",
    highlights: ["ネオンとLEDが輝く独特な夜景","アニメ・ゲームの聖地","電気街の活気ある雰囲気","サブカルチャーを体感"],
    recommendedTimes: ["夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "秋葉原駅から徒歩1分",
  },
  {
    id: 56,
    name: "表参道イルミネーション",
    duration: 60,
    distance: 4.5,
    area: "表参道",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "ケヤキ並木のイルミネーションが美しい冬の定番夜景スポット。",
    startPoint: "表参道駅",
    endPoint: "原宿駅",
    waypoints: ["表参道ヒルズ", "ケヤキ並木"],
    durationNote: "イルミネーションをゆっくり楽しむ時間です",
    highlights: ["ケヤキ並木のイルミネーション","高級ブランド店のディスプレイ","冬の定番デートスポット","表参道ヒルズでショッピング"],
    recommendedTimes: ["夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "表参道駅から徒歩1分、冬季限定",
  },

  // 春の季節限定コース（6個）
  {
    id: 57,
    name: "飛鳥山公園の桜",
    duration: 60,
    distance: 4.2,
    area: "王子",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "江戸時代から続く桜の名所。約650本の桜が咲き誇ります。",
    startPoint: "王子駅",
    endPoint: "西ヶ原駅",
    waypoints: ["飛鳥山公園"],
    durationNote: "公園内を散策し、桜を楽しむ時間です",
    highlights: ["約650本の桜が咲き誇る","江戸時代からの桜の名所","飛鳥山モノレールも楽しい","北区の桜の名所として有名"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "王子駅から徒歩1分、公園内は坂あり",
  },
  {
    id: 58,
    name: "石神井公園の桜と新緑",
    duration: 90,
    distance: 6.9,
    area: "石神井",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "池の周りを彩る桜と新緑。ボートからの眺めも楽しめます。",
    startPoint: "石神井公園駅",
    endPoint: "大泉学園駅",
    waypoints: ["石神井公園", "三宝寺池", "石神井池"],
    durationNote: "公園内を散策し、ボート遊びも楽しむ時間です",
    highlights: ["2つの池を巡る散策コース","ボートから眺める桜","野鳥観察も楽しめる","静かな住宅街の中のオアシス"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "石神井公園駅から徒歩7分",
  },
  {
    id: 59,
    name: "隅田公園桜まつり",
    duration: 60,
    distance: 4.6,
    area: "浅草",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "隅田川沿いに約1,000本の桜。スカイツリーと桜のコラボレーション。",
    startPoint: "浅草駅",
    endPoint: "押上駅",
    waypoints: ["隅田公園", "桜橋"],
    durationNote: "桜を鑑賞しながら川沿いを散策する時間です",
    highlights: ["約1,000本の桜並木","スカイツリーと桜のコラボ","桜まつり期間は屋台も出店","浅草観光と組み合わせ可能"],
    recommendedTimes: ["朝","昼","夜"],
    difficulty: "初心者向け",
    accessInfo: "浅草駅から徒歩5分、平坦な河川敷",
  },
  {
    id: 60,
    name: "砧公園ファミリー桜散歩",
    duration: 90,
    distance: 7.1,
    area: "用賀",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "広大な芝生と約840本の桜。ピクニックにも最適な公園です。",
    startPoint: "用賀駅",
    endPoint: "千歳船橋駅",
    waypoints: ["砧公園", "ファミリーパーク"],
    durationNote: "公園内を散策し、ピクニックを楽しむ時間です",
    highlights: ["約840本の桜","広大な芝生でピクニック","ファミリーに人気","静かにお花見を楽しめる"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "用賀駅からバス10分、広大な公園",
  },
  {
    id: 61,
    name: "播磨坂さくら並木",
    duration: 30,
    distance: 2.3,
    area: "文京区",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "約150本の桜のトンネル。地元で愛される隠れた名所です。",
    startPoint: "茗荷谷駅",
    endPoint: "江戸川橋駅",
    waypoints: ["播磨坂さくら並木"],
    durationNote: "桜のトンネルをゆっくり歩く時間です",
    highlights: ["約150本の桜のトンネル","地元で愛される隠れた名所","桜まつりも開催","穴場の桜スポット"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "茗荷谷駅から徒歩5分、坂道あり",
  },
  {
    id: 62,
    name: "光が丘公園の桜",
    duration: 60,
    distance: 4.8,
    area: "光が丘",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "広大な芝生広場と桜並木。ゆったりとした春の散歩が楽しめます。",
    startPoint: "光が丘駅",
    endPoint: "練馬春日町駅",
    waypoints: ["光が丘公園"],
    durationNote: "広々とした公園で桜を楽しむ時間です",
    highlights: ["広大な芝生広場","桜並木のトンネル","スポーツ施設も充実","家族でのんびり過ごせる"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "光が丘駅から徒歩5分",
  },

  // 夏の季節限定コース（8個）
  {
    id: 63,
    name: "葛西臨海公園海風散歩",
    duration: 90,
    distance: 7.3,
    area: "葛西",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "海沿いの公園で潮風を感じながら散策。観覧車からの眺めも楽しめます。",
    startPoint: "葛西臨海公園駅",
    endPoint: "葛西駅",
    waypoints: ["葛西臨海公園", "ダイヤと花の大観覧車"],
    durationNote: "公園内を散策し、観覧車も楽しむ時間です",
    highlights: ["ダイヤと花の大観覧車","水族館も楽しめる","海風が心地よい","バーベキュー広場もあり"],
    recommendedTimes: ["朝","昼","夕方"],
    difficulty: "初心者向け",
    accessInfo: "葛西臨海公園駅から徒歩1分",
  },
  {
    id: 64,
    name: "砧公園の木陰散歩",
    duration: 60,
    distance: 4.5,
    area: "用賀",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "木陰が多く夏でも涼しい公園。広い芝生でリフレッシュできます。",
    startPoint: "用賀駅",
    endPoint: "祖師ヶ谷大蔵駅",
    waypoints: ["砧公園"],
    durationNote: "木陰で涼みながら散策する時間です",
    highlights: ["木陰が豊富で涼しい","広い芝生でリフレッシュ","世田谷美術館も隣接","静かにくつろげる"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "用賀駅からバス10分",
  },
  {
    id: 65,
    name: "水元公園の涼散歩",
    duration: 90,
    distance: 6.7,
    area: "金町",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "都内最大級の水郷公園。水辺の涼しさと豊かな自然を楽しめます。",
    startPoint: "金町駅",
    endPoint: "亀有駅",
    waypoints: ["水元公園", "小合溜井"],
    durationNote: "水辺を散策し、自然を楽しむ時間です",
    highlights: ["都内最大級の水郷公園","ポプラ並木が美しい","釣りやバードウォッチング","広大な自然を満喫"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "金町駅からバス20分",
  },
  {
    id: 66,
    name: "駒沢オリンピック公園",
    duration: 60,
    distance: 4.3,
    area: "駒沢",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "木陰が豊富なジョギングコース。スポーツ施設も充実しています。",
    startPoint: "駒沢大学駅",
    endPoint: "桜新町駅",
    waypoints: ["駒沢オリンピック公園"],
    durationNote: "公園内を散策し、運動も楽しむ時間です",
    highlights: ["オリンピック施設のある公園","ジョギングコースが整備","木陰が多く涼しい","スポーツを楽しめる"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "駒沢大学駅から徒歩15分",
  },
  {
    id: 67,
    name: "野川公園の自然散策",
    duration: 90,
    distance: 7.0,
    area: "調布",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "野川沿いの自然豊かな公園。川のせせらぎが涼しげです。",
    startPoint: "西武多摩川駅",
    endPoint: "武蔵境駅",
    waypoints: ["野川公園", "野川"],
    durationNote: "川沿いを散策し、自然を楽しむ時間です",
    highlights: ["野川のせせらぎ","自然観察園も楽しめる","木陰で涼む","バーベキュー広場もあり"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "西武多摩川駅から徒歩15分",
  },
  {
    id: 68,
    name: "芝公園の緑陰散歩",
    duration: 30,
    distance: 2.4,
    area: "芝公園",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "東京タワーを眺めながら木陰で涼む都心のオアシス。",
    startPoint: "芝公園駅",
    endPoint: "御成門駅",
    waypoints: ["芝公園"],
    durationNote: "木陰で涼みながら散策する時間です",
    highlights: ["東京タワーを眺めながら涼む","歴史ある都市公園","増上寺も近い","都心のオアシス"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "芝公園駅から徒歩2分",
  },
  {
    id: 69,
    name: "舎人公園の夏散歩",
    duration: 60,
    distance: 4.7,
    area: "舎人",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "広大な芝生と大池。日暮里・舎人ライナーでアクセス便利です。",
    startPoint: "舎人公園駅",
    endPoint: "見沼代親水公園駅",
    waypoints: ["舎人公園"],
    durationNote: "広々とした公園を散策する時間です",
    highlights: ["日暮里舎人ライナーでアクセス","大池を囲む広大な芝生","スポーツ施設も充実","穴場の大型公園"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "舎人公園駅から徒歩1分",
  },
  {
    id: 70,
    name: "多摩川河川敷サイクリングロード",
    duration: 90,
    distance: 7.5,
    area: "多摩川",
    seasons: ["夏"],
    weatherStyles: ["晴天", "曇天"],
    description: "多摩川沿いの広々とした遊歩道。川風が心地よい夏の定番コース。",
    startPoint: "二子玉川駅",
    endPoint: "登戸駅",
    waypoints: ["多摩川河川敷", "二子橋"],
    durationNote: "河川敷をゆっくり歩き、川風を楽しむ時間です",
    highlights: ["多摩川の開放的な景色","サイクリングも可能","川風が心地よい","神奈川県側へも渡れる"],
    recommendedTimes: ["朝","昼","夕方"],
    difficulty: "初心者向け",
    accessInfo: "二子玉川駅から徒歩5分、平坦な河川敷",
  },

  // 秋の季節限定コース（6個）
  {
    id: 71,
    name: "高尾山紅葉ハイキング",
    duration: 90,
    distance: 6.5,
    area: "高尾",
    seasons: ["秋"],
    weatherStyles: ["晴天", "曇天"],
    description: "都心から1時間の紅葉の名所。ケーブルカーで気軽にアクセスできます。",
    startPoint: "高尾山口駅",
    endPoint: "高尾山頂",
    waypoints: ["高尾山ケーブルカー", "薬王院"],
    durationNote: "ハイキングと紅葉鑑賞、参拝を楽しむ時間です",
    highlights: ["ミシュラン三ツ星の山","ケーブルカーで楽々アクセス","薬王院で参拝","紅葉の名所として有名"],
    recommendedTimes: ["朝","昼"],
    difficulty: "中級者向け",
    accessInfo: "高尾山口駅から徒歩5分、山道あり",
  },
  {
    id: 72,
    name: "殿ヶ谷戸庭園の紅葉",
    duration: 30,
    distance: 2.1,
    area: "国分寺",
    seasons: ["秋"],
    weatherStyles: ["晴天", "曇天"],
    description: "崖線の地形を活かした庭園。紅葉の美しさは都内屈指です。",
    startPoint: "国分寺駅",
    endPoint: "西国分寺駅",
    waypoints: ["殿ヶ谷戸庭園"],
    durationNote: "庭園内をゆっくり散策し、紅葉を楽しむ時間です",
    highlights: ["崖線地形を活かした庭園","紅葉の美しさは都内屈指","湧水池が見どころ","穴場の紅葉スポット"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "国分寺駅から徒歩2分、入園料150円",
  },
  {
    id: 73,
    name: "井の頭公園紅葉散策",
    duration: 60,
    distance: 4.4,
    area: "吉祥寺",
    seasons: ["秋"],
    weatherStyles: ["晴天", "曇天"],
    description: "池の周りを彩る紅葉。ボートから眺める紅葉も格別です。",
    startPoint: "吉祥寺駅",
    endPoint: "井の頭公園駅",
    waypoints: ["井の頭恩賜公園", "井の頭池"],
    durationNote: "公園内を散策し、ボートで紅葉を楽しむ時間です",
    highlights: ["池の周りを彩る紅葉","ボートから眺める紅葉","動物園も隣接","吉祥寺散策も楽しめる"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "吉祥寺駅から徒歩5分",
  },
  {
    id: 74,
    name: "旧古河庭園の秋バラと紅葉",
    duration: 60,
    distance: 4.0,
    area: "西ヶ原",
    seasons: ["秋"],
    weatherStyles: ["晴天", "曇天"],
    description: "洋館と日本庭園が融合。秋バラと紅葉の共演が見事です。",
    startPoint: "上中里駅",
    endPoint: "駒込駅",
    waypoints: ["旧古河庭園"],
    durationNote: "庭園内を散策し、バラと紅葉を楽しむ時間です",
    highlights: ["洋館と日本庭園の融合","秋バラと紅葉の共演","大正ロマンの雰囲気","写真映えスポット多数"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "上中里駅から徒歩7分、入園料150円",
  },
  {
    id: 75,
    name: "浜離宮恩賜庭園秋景色",
    duration: 60,
    distance: 4.1,
    area: "汐留",
    seasons: ["秋"],
    weatherStyles: ["晴天", "曇天"],
    description: "潮入の池と紅葉のコントラスト。都心のビル群を背景にした紅葉が美しい。",
    startPoint: "汐留駅",
    endPoint: "新橋駅",
    waypoints: ["浜離宮恩賜庭園"],
    durationNote: "庭園内を散策し、紅葉を楽しむ時間です",
    highlights: ["潮入の池と紅葉","都心のビル群を背景に紅葉","お茶屋で抹茶を楽しめる","築地市場からも近い"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "汐留駅から徒歩7分、入園料300円",
  },
  {
    id: 76,
    name: "石神井公園紅葉巡り",
    duration: 90,
    distance: 6.8,
    area: "石神井",
    seasons: ["秋"],
    weatherStyles: ["晴天", "曇天"],
    description: "三宝寺池と石神井池の周りを彩る紅葉。静かな秋の散策が楽しめます。",
    startPoint: "石神井公園駅",
    endPoint: "大泉学園駅",
    waypoints: ["石神井公園", "三宝寺池"],
    durationNote: "公園内をゆっくり散策し、紅葉を楽しむ時間です",
    highlights: ["三宝寺池と石神井池","静かな紅葉散策","野鳥観察も楽しめる","落ち着いた雰囲気"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "石神井公園駅から徒歩7分",
  },

  // 冬の季節限定コース（6個）
  {
    id: 77,
    name: "大手町イルミネーション",
    duration: 30,
    distance: 2.2,
    area: "大手町",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "オフィス街のイルミネーションが幻想的。仕事帰りに立ち寄れます。",
    startPoint: "大手町駅",
    endPoint: "東京駅",
    waypoints: ["大手町仲通り"],
    durationNote: "イルミネーションをゆっくり楽しむ時間です",
    highlights: ["オフィス街のイルミネーション","東京駅まで歩いて行ける","仕事帰りに立ち寄れる","皇居も近い"],
    recommendedTimes: ["夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "大手町駅から徒歩1分",
  },
  {
    id: 78,
    name: "よみうりランド ジュエルミネーション",
    duration: 90,
    distance: 6.2,
    area: "稲城",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "関東最大級のイルミネーション。550万球の光の世界です。",
    startPoint: "京王よみうりランド駅",
    endPoint: "よみうりランド",
    waypoints: ["よみうりランド"],
    durationNote: "イルミネーションを見て回る時間です",
    highlights: ["550万球の圧巻のイルミネーション","関東最大級の規模","遊園地アトラクションも","スカイシャトルからの眺めも"],
    recommendedTimes: ["夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "京王よみうりランド駅からゴンドラ10分、入園料別途",
  },
  {
    id: 79,
    name: "カレッタ汐留イルミネーション",
    duration: 30,
    distance: 2.0,
    area: "汐留",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天", "雨天"],
    description: "屋内でも楽しめるイルミネーション。音楽とのコラボレーションが見事です。",
    startPoint: "汐留駅",
    endPoint: "新橋駅",
    waypoints: ["カレッタ汐留"],
    durationNote: "イルミネーションと音楽を楽しむ時間です",
    highlights: ["屋内でも楽しめる","音楽との美しいコラボレーション","雨でも安心","新橋グルメも楽しめる"],
    recommendedTimes: ["夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "汐留駅直結、無料",
  },
  {
    id: 80,
    name: "代々木公園冬景色",
    duration: 60,
    distance: 4.3,
    area: "原宿",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "冬の澄んだ空気の中、静かな公園を散策。都会の喧騒を忘れられます。",
    startPoint: "原宿駅",
    endPoint: "代々木公園駅",
    waypoints: ["代々木公園"],
    durationNote: "静かな公園をゆっくり散策する時間です",
    highlights: ["冬の澄んだ空気で散策","明治神宮も近い","静かな公園でリフレッシュ","広い芝生でくつろげる"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "原宿駅から徒歩3分",
  },
  {
    id: 81,
    name: "日比谷公園冬散歩",
    duration: 30,
    distance: 2.3,
    area: "日比谷",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "都心の憩いの場。冬の凛とした空気が心地よい散歩道です。",
    startPoint: "日比谷駅",
    endPoint: "有楽町駅",
    waypoints: ["日比谷公園"],
    durationNote: "公園内をゆっくり散策する時間です",
    highlights: ["都心の憩いの場","冬の凛とした空気","日比谷野外音楽堂も近い","有楽町でショッピングも"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "日比谷駅から徒歩2分",
  },
  {
    id: 82,
    name: "東京ミッドタウン冬の庭",
    duration: 60,
    distance: 4.0,
    area: "六本木",
    seasons: ["冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "洗練されたイルミネーションと冬の庭園。大人の冬散歩に最適です。",
    startPoint: "六本木駅",
    endPoint: "乃木坂駅",
    waypoints: ["東京ミッドタウン", "檜町公園"],
    durationNote: "イルミネーションと庭園を楽しむ時間です",
    highlights: ["洗練されたイルミネーション","スターライトガーデンが美しい","美術館やショップも充実","大人の冬散歩に最適"],
    recommendedTimes: ["夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "六本木駅から徒歩5分",
  },

  // グルメ散歩コース（8個）
  {
    id: 83,
    name: "戸越銀座商店街グルメ巡り",
    duration: 60,
    distance: 4.2,
    area: "戸越銀座",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "都内最長の商店街で食べ歩き。コロッケや和菓子が人気です。",
    startPoint: "戸越銀座駅",
    endPoint: "戸越公園駅",
    waypoints: ["戸越銀座商店街"],
    durationNote: "食べ歩きとショッピングを楽しむ時間です",
    highlights: ["都内最長1.3kmの商店街","コロッケグランプリ常連店","食べ歩きに最適","下町情緒あふれる雰囲気"],
    recommendedTimes: ["昼","夕方"],
    difficulty: "初心者向け",
    accessInfo: "戸越銀座駅から徒歩1分",
  },
  {
    id: 84,
    name: "佃・月島もんじゃストリート",
    duration: 60,
    distance: 4.5,
    area: "月島",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "もんじゃ焼きの聖地。70店以上のもんじゃ屋が軒を連ねます。",
    startPoint: "月島駅",
    endPoint: "勝どき駅",
    waypoints: ["もんじゃストリート"],
    durationNote: "もんじゃ焼きを食べながら散策する時間です",
    highlights: ["70店以上のもんじゃ屋","元祖もんじゃを堪能","佃煮も名物","下町情緒あふれる"],
    recommendedTimes: ["昼","夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "月島駅から徒歩1分",
  },
  {
    id: 85,
    name: "巣鴨地蔵通り商店街",
    duration: 30,
    distance: 2.4,
    area: "巣鴨",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "おばあちゃんの原宿。塩大福や赤パンツが名物の下町商店街です。",
    startPoint: "巣鴨駅",
    endPoint: "庚申塚駅",
    waypoints: ["巣鴨地蔵通り商店街"],
    durationNote: "商店街で食べ歩きやショッピングを楽しむ時間です",
    highlights: ["とげぬき地蔵で有名","塩大福の名店が多数","赤パンツが名物","毎月4の日は縁日"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "巣鴨駅から徒歩5分",
  },
  {
    id: 86,
    name: "両国ちゃんこ鍋巡り",
    duration: 60,
    distance: 4.0,
    area: "両国",
    seasons: ["秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "相撲の街で本格ちゃんこ鍋。江戸東京博物館も楽しめます。",
    startPoint: "両国駅",
    endPoint: "森下駅",
    waypoints: ["両国国技館", "江戸東京博物館"],
    durationNote: "ちゃんこ鍋と観光を楽しむ時間です",
    highlights: ["元力士が営むちゃんこ屋","相撲観戦と組み合わせ可能","江戸東京博物館も近い","回向院で歴史を学ぶ"],
    recommendedTimes: ["昼","夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "両国駅から徒歩3分",
  },
  {
    id: 87,
    name: "門前仲町深川めし散歩",
    duration: 60,
    distance: 4.3,
    area: "門前仲町",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "深川めしと下町グルメ。富岡八幡宮の参拝も楽しめます。",
    startPoint: "門前仲町駅",
    endPoint: "清澄白河駅",
    waypoints: ["富岡八幡宮", "深大寺通り"],
    durationNote: "グルメと参拝を楽しむ時間です",
    highlights: ["名物・深川めし","富岡八幡宮で参拝","清澄庭園も近い","下町グルメを堪能"],
    recommendedTimes: ["昼","夕方"],
    difficulty: "初心者向け",
    accessInfo: "門前仲町駅から徒歩3分",
  },
  {
    id: 88,
    name: "人形町甘酒横丁",
    duration: 30,
    distance: 2.2,
    area: "人形町",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "老舗の和菓子店やせんべい屋が並ぶ情緒ある通り。",
    startPoint: "人形町駅",
    endPoint: "水天宮前駅",
    waypoints: ["甘酒横丁"],
    durationNote: "和菓子を食べながら散策する時間です",
    highlights: ["老舗の和菓子店が並ぶ","人形焼きやせんべいが名物","水天宮で安産祈願","情緒ある通り"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "人形町駅から徒歩2分",
  },
  {
    id: 89,
    name: "高円寺阿波おどり通り",
    duration: 60,
    distance: 4.1,
    area: "高円寺",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "個性的な飲食店が集まるサブカルの街。古着屋巡りも楽しめます。",
    startPoint: "高円寺駅",
    endPoint: "新高円寺駅",
    waypoints: ["高円寺純情商店街"],
    durationNote: "グルメと古着屋巡りを楽しむ時間です",
    highlights: ["個性的な飲食店が多数","古着屋巡りも楽しい","阿波おどりの街","サブカルチャーの発信地"],
    recommendedTimes: ["昼","夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "高円寺駅から徒歩1分",
  },
  {
    id: 90,
    name: "中野ブロードウェイ探検",
    duration: 60,
    distance: 4.0,
    area: "中野",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天", "雨天"],
    description: "サブカルチャーの聖地。マニアックなショップとグルメが楽しめます。",
    startPoint: "中野駅",
    endPoint: "新中野駅",
    waypoints: ["中野ブロードウェイ"],
    durationNote: "サブカル探検とグルメを楽しむ時間です",
    highlights: ["サブカルチャーの聖地","まんだらけなど有名店多数","雨でも楽しめる","中野サンプラザも近い"],
    recommendedTimes: ["昼","夕方"],
    difficulty: "初心者向け",
    accessInfo: "中野駅から徒歩5分、屋内施設",
  },

  // 歴史・文化コース（6個）
  {
    id: 91,
    name: "柴又帝釈天参道",
    duration: 60,
    distance: 4.4,
    area: "柴又",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "寅さんの街。江戸情緒あふれる参道と帝釈天を巡ります。",
    startPoint: "柴又駅",
    endPoint: "京成金町駅",
    waypoints: ["柴又帝釈天", "寅さん記念館"],
    durationNote: "参拝と観光を楽しむ時間です",
    highlights: ["寅さんの舞台","江戸情緒あふれる参道","草だんごが名物","矢切の渡しも近い"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "柴又駅から徒歩3分",
  },
  {
    id: 92,
    name: "根津神社つつじ散歩",
    duration: 30,
    distance: 2.3,
    area: "根津",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "約3,000株のつつじが咲く歴史ある神社。文京区の隠れた名所です。",
    startPoint: "根津駅",
    endPoint: "千駄木駅",
    waypoints: ["根津神社"],
    durationNote: "つつじを鑑賞しながら参拝する時間です",
    highlights: ["約3,000株のつつじ","国の重要文化財の社殿","乙女稲荷神社も見どころ","谷根千散策と組み合わせ"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "根津駅から徒歩5分",
  },
  {
    id: 93,
    name: "増上寺と東京タワー",
    duration: 60,
    distance: 4.2,
    area: "芝公園",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "徳川家の菩提寺と東京タワーのコントラスト。歴史と現代が交差します。",
    startPoint: "芝公園駅",
    endPoint: "大門駅",
    waypoints: ["増上寺", "東京タワー"],
    durationNote: "参拝と観光を楽しむ時間です",
    highlights: ["徳川家の菩提寺","東京タワーとの共演","大門の赤い門が印象的","歴史と現代の融合"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "芝公園駅から徒歩3分",
  },
  {
    id: 94,
    name: "護国寺と音羽の杜",
    duration: 30,
    distance: 2.4,
    area: "護国寺",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "徳川綱吉ゆかりの寺院。静かな境内で心が落ち着きます。",
    startPoint: "護国寺駅",
    endPoint: "江戸川橋駅",
    waypoints: ["護国寺"],
    durationNote: "境内をゆっくり参拝する時間です",
    highlights: ["徳川綱吉ゆかりの寺院","静かな境内で心が落ち着く","本堂は国の重要文化財","講談社野間記念館も近い"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "護国寺駅から徒歩1分",
  },
  {
    id: 95,
    name: "寛永寺と上野の杜",
    duration: 90,
    distance: 6.6,
    area: "上野",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["晴天", "曇天"],
    description: "徳川家ゆかりの寺院群。上野公園の歴史散策が楽しめます。",
    startPoint: "上野駅",
    endPoint: "日暮里駅",
    waypoints: ["寛永寺", "上野東照宮", "清水観音堂"],
    durationNote: "寺社を巡り、歴史を学ぶ時間です",
    highlights: ["徳川家ゆかりの寺院群","上野の杜の歴史を巡る","上野東照宮の金色の社殿","博物館・美術館も近い"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "上野駅から徒歩5分",
  },
  {
    id: 96,
    name: "亀戸天神と藤の花",
    duration: 60,
    distance: 4.3,
    area: "亀戸",
    seasons: ["春"],
    weatherStyles: ["晴天", "曇天"],
    description: "学問の神様と美しい藤の花。スカイツリーを背景にした境内が絶景です。",
    startPoint: "亀戸駅",
    endPoint: "錦糸町駅",
    waypoints: ["亀戸天神社"],
    durationNote: "藤の花を鑑賞しながら参拝する時間です",
    highlights: ["学問の神様を祀る","藤の花は都内屈指","スカイツリーを背景に写真","亀戸餃子も名物"],
    recommendedTimes: ["朝","昼"],
    difficulty: "初心者向け",
    accessInfo: "亀戸駅から徒歩15分",
  },

  // 雨天対応コース（4個）
  {
    id: 97,
    name: "池袋サンシャインシティ",
    duration: 60,
    distance: 4.0,
    area: "池袋",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["雨天", "曇天"],
    description: "水族館、展望台、ショッピングが楽しめる複合施設。雨でも一日遊べます。",
    startPoint: "池袋駅",
    endPoint: "東池袋駅",
    waypoints: ["サンシャインシティ", "サンシャイン水族館"],
    durationNote: "施設内を見て回り、ショッピングを楽しむ時間です",
    highlights: ["水族館で癒される","展望台から360度の眺望","プラネタリウムも","ナンジャタウンも楽しめる"],
    recommendedTimes: ["昼","夕方","夜"],
    difficulty: "初心者向け",
    accessInfo: "池袋駅から徒歩8分、屋内施設",
  },
  {
    id: 98,
    name: "お台場ヴィーナスフォート",
    duration: 90,
    distance: 6.5,
    area: "お台場",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["雨天", "曇天"],
    description: "屋内型テーマパーク。中世ヨーロッパの街並みを再現した商業施設です。",
    startPoint: "青海駅",
    endPoint: "お台場海浜公園駅",
    waypoints: ["パレットタウン", "チームラボボーダレス"],
    durationNote: "屋内施設をゆっくり見て回る時間です",
    highlights: ["中世ヨーロッパの街並み","チームラボの体験型アート","車の展示も楽しい","お台場観光の中心"],
    recommendedTimes: ["昼","夕方"],
    difficulty: "初心者向け",
    accessInfo: "青海駅から徒歩3分、屋内施設",
  },
  {
    id: 99,
    name: "二子玉川ライズ",
    duration: 60,
    distance: 4.2,
    area: "二子玉川",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["雨天", "曇天"],
    description: "ショッピングとグルメが充実。雨の日でも快適に過ごせる商業施設です。",
    startPoint: "二子玉川駅",
    endPoint: "二子新地駅",
    waypoints: ["二子玉川ライズ"],
    durationNote: "ショッピングとグルメを楽しむ時間です",
    highlights: ["おしゃれなショッピングモール","蔦屋家電も入居","多摩川を眺めながら休憩","雨でも快適に過ごせる"],
    recommendedTimes: ["昼","夕方"],
    difficulty: "初心者向け",
    accessInfo: "二子玉川駅直結、屋内施設",
  },
  {
    id: 100,
    name: "立川ルミネ・伊勢丹",
    duration: 30,
    distance: 2.1,
    area: "立川",
    seasons: ["春", "夏", "秋", "冬"],
    weatherStyles: ["雨天", "曇天"],
    description: "立川駅直結の商業施設。雨を気にせずショッピングが楽しめます。",
    startPoint: "立川駅",
    endPoint: "立川北駅",
    waypoints: ["立川ルミネ"],
    durationNote: "駅直結でショッピングを楽しむ時間です",
    highlights: ["駅直結で雨でも安心","百貨店とファッションビル","昭和記念公園へのアクセス良好","映画館も併設"],
    recommendedTimes: ["昼","夕方"],
    difficulty: "初心者向け",
    accessInfo: "立川駅直結、屋内施設",
  },
];
